import IconAlertTriangle from './tabler/IconAlertTriangle.svelte';
import IconBell from './tabler/IconBell.svelte';
import IconBook from './tabler/IconBook.svelte';
import IconBolt from './tabler/IconBolt.svelte';
import IconBrain from './tabler/IconBrain.svelte';
import IconBuildingCommunity from './tabler/IconBuildingCommunity.svelte';
import IconCheck from './tabler/IconCheck.svelte';
import IconCircleCheck from './tabler/IconCircleCheck.svelte';
import IconCircleX from './tabler/IconCircleX.svelte';
import IconClipboardList from './tabler/IconClipboardList.svelte';
import IconClockHour4 from './tabler/IconClockHour4.svelte';
import IconCamera from './tabler/IconCamera.svelte';
import IconCopy from './tabler/IconCopy.svelte';
import IconCpu from './tabler/IconCpu.svelte';
import IconDatabase from './tabler/IconDatabase.svelte';
import IconEdit from './tabler/IconEdit.svelte';
import IconFile from './tabler/IconFile.svelte';
import IconFileText from './tabler/IconFileText.svelte';
import IconFileTypePdf from './tabler/IconFileTypePdf.svelte';
import IconFingerprint from './tabler/IconFingerprint.svelte';
import IconFlower from './tabler/IconFlower.svelte';
import IconFolder from './tabler/IconFolder.svelte';
import IconGauge from './tabler/IconGauge.svelte';
import IconGitBranch from './tabler/IconGitBranch.svelte';
import IconInbox from './tabler/IconInbox.svelte';
import IconInfoCircle from './tabler/IconInfoCircle.svelte';
import IconJson from './tabler/IconJson.svelte';
import IconLogin2 from './tabler/IconLogin2.svelte';
import IconMoon from './tabler/IconMoon.svelte';
import IconMusic from './tabler/IconMusic.svelte';
import IconNetwork from './tabler/IconNetwork.svelte';
import IconPackage from './tabler/IconPackage.svelte';
import IconPalette from './tabler/IconPalette.svelte';
import IconPencil from './tabler/IconPencil.svelte';
import IconPhoto from './tabler/IconPhoto.svelte';
import IconPlant from './tabler/IconPlant.svelte';
import IconPlugConnected from './tabler/IconPlugConnected.svelte';
import IconProgress from './tabler/IconProgress.svelte';
import IconQuestionMark from './tabler/IconQuestionMark.svelte';
import IconReceipt from './tabler/IconReceipt.svelte';
import IconRobot from './tabler/IconRobot.svelte';
import IconRocket from './tabler/IconRocket.svelte';
import IconRotateClockwise from './tabler/IconRotateClockwise.svelte';
import IconSearch from './tabler/IconSearch.svelte';
import IconServer from './tabler/IconServer.svelte';
import IconSettings from './tabler/IconSettings.svelte';
import IconShieldCheck from './tabler/IconShieldCheck.svelte';
import IconShieldLock from './tabler/IconShieldLock.svelte';
import IconShieldLock from './tabler/IconShieldLock.svelte';
import IconSignature from './tabler/IconSignature.svelte';
import IconSparkles from './tabler/IconSparkles.svelte';
import IconSun from './tabler/IconSun.svelte';
import IconTarget from './tabler/IconTarget.svelte';
import IconVideo from './tabler/IconVideo.svelte';
import IconX from './tabler/IconX.svelte';

export const ServiceIcon = IconServer;
export const ArtifactIcon = IconPackage;
export const EnvironmentIcon = IconTarget;
export const DeploymentIcon = IconRocket;
export const NotificationIcon = IconBell;
export const PaymentIcon = IconReceipt;
export const PolicyIcon = IconShieldCheck;
export const SecurityIcon = IconShieldLock;
export const OrganizationIcon = IconBuildingCommunity;
export const LlmIcon = IconBrain;
export const AppearanceIcon = IconPalette;
export const RollbackIcon = IconRotateClockwise;
export const BlossomIcon = IconFlower;
export const ProtectedIcon = IconShieldLock;
export const WarningIcon = IconAlertTriangle;
export const SuccessIcon = IconCircleCheck;
export const ErrorIcon = IconCircleX;
export const InfoIcon = IconInfoCircle;
export const UnknownIcon = IconQuestionMark;
export const CopyIcon = IconCopy;
export const CloseIcon = IconX;
export const CheckIcon = IconCheck;
export const SbomIcon = IconClipboardList;
export const SignatureIcon = IconSignature;
export const EmptyIcon = IconInbox;
export const SunIcon = IconSun;
export const MoonIcon = IconMoon;
export const LoginIcon = IconLogin2;
export const SearchIcon = IconSearch;
export const EditIcon = IconEdit;
export const PendingIcon = IconClockHour4;
export const CameraIcon = IconCamera;
export const RelayIcon = IconPlugConnected;
export const ConfiguredIcon = IconSettings;
export const RepositoryIcon = IconGitBranch;
export const SoulIcon = IconBrain;
export const IdentityIcon = IconFingerprint;
export const AvatarIcon = IconPalette;
export const ProfileIcon = IconPencil;
export const MemoryIcon = IconDatabase;
export const SeedIcon = IconPlant;
export const WorkspaceIcon = IconFolder;
export const ProgressIcon = IconProgress;
export const TemplateIcon = IconSparkles;
export const LightweightIcon = IconBolt;
export const StandardIcon = IconRobot;
export const HeavyIcon = IconGauge;
export const MLFabricIcon = IconNetwork;
export const AcceleratorIcon = IconCpu;
export const DocsIcon = IconBook;

export const ImageFileIcon = IconPhoto;
export const VideoFileIcon = IconVideo;
export const AudioFileIcon = IconMusic;
export const JsonFileIcon = IconJson;
export const TextFileIcon = IconFileText;
export const PdfFileIcon = IconFileTypePdf;
export const GenericFileIcon = IconFile;

export function blossomContentTypeIcon(contentType) {
  const normalized = (contentType || '').toLowerCase();

  if (normalized.startsWith('image/')) return ImageFileIcon;
  if (normalized.startsWith('video/')) return VideoFileIcon;
  if (normalized.startsWith('audio/')) return AudioFileIcon;
  if (normalized.includes('json')) return JsonFileIcon;
  if (normalized.startsWith('text/') || normalized.includes('text')) return TextFileIcon;
  if (normalized.includes('pdf')) return PdfFileIcon;

  return GenericFileIcon;
}
