package controlplane

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strings"
	"time"

	"fiatjaf.com/nostr"
	"github.com/google/uuid"
	adapterruntime "github.com/openagentsinc/bahia/internal/adapters/runtime"
	"github.com/openagentsinc/bahia/internal/adapters/secrets"
	"github.com/openagentsinc/bahia/internal/api/dto"
	"github.com/openagentsinc/bahia/internal/auth"
	"github.com/openagentsinc/bahia/internal/domain"
	"github.com/openagentsinc/bahia/internal/readmodel"
	"github.com/openagentsinc/bahia/internal/repository"
	"github.com/openagentsinc/bahia/internal/service"
	"go.uber.org/zap"
)

const (
	EncryptedOperationServiceSecretsList   = "services.secrets.list"
	EncryptedOperationServiceSecretsCreate = "services.secrets.create"
	EncryptedOperationServiceSecretsUpdate = "services.secrets.update"
	EncryptedOperationServiceSecretsDelete = "services.secrets.delete"
	EncryptedOperationServiceSecretsReveal = "services.secrets.reveal"

	ContextVMMethodServiceSecretsList   = "services/secrets-list"
	ContextVMMethodServiceSecretsCreate = "services/secrets-create"
	ContextVMMethodServiceSecretsUpdate = "services/secrets-update"
	ContextVMMethodServiceSecretsDelete = "services/secrets-delete"
	ContextVMMethodServiceSecretsReveal = "services/secrets-reveal"

	EncryptedOperationDeploymentRunLogsGet = "deployments.run_logs.get"
	ContextVMMethodDeploymentRunLogsGet    = "deployments/run-logs-get"
	ContextVMMethodServiceUpdate           = "service/update"
	ContextVMMethodServiceDelete           = "service/delete"
	ContextVMMethodEnvironmentCreate       = "environment/create"
	ContextVMMethodEnvironmentGetDetails   = "environment/get-details"
	ContextVMMethodEnvironmentUpdate       = "environment/update"
	ContextVMMethodEnvironmentDelete       = "environment/delete"
	ContextVMMethodArtifactRegister        = "artifact/register"
	ContextVMMethodArtifactImportObserved  = "artifact/import-observed"

	// Notification channel mutation encrypted operation names matching
	// NOTIFICATION_ENCRYPTED_OPERATIONS in web/src/lib/stores/notifications.svelte.js.
	EncryptedOperationNotificationChannelsCreate = "notifications.channels.create"
	EncryptedOperationNotificationChannelsUpdate = "notifications.channels.update"
	EncryptedOperationNotificationChannelsDelete = "notifications.channels.delete"

	// ContextVM method forms generated by the web's contextVMMethod() for
	// notifications.channels.* encrypted operations. Gift-wrapped requests
	// arrive with these as the JSON-RPC method.
	ContextVMMethodNotificationChannelsCreate = "notifications/channels-create"
	ContextVMMethodNotificationChannelsUpdate = "notifications/channels-update"
	ContextVMMethodNotificationChannelsDelete = "notifications/channels-delete"

	// Phase 3 N1: notification channel intent method aliases. Retained for
	// intent processor replay and CLI tools that send notification/* methods.
	ContextVMMethodNotificationChannelCreate = "notification/create"
	ContextVMMethodNotificationChannelUpdate = "notification/update"
	ContextVMMethodNotificationChannelDelete = "notification/delete"

	EncryptedOperationArtifactSignaturesVerify = "artifacts.signatures.verify"
)

// RunLogFetcher is the encrypted request contract for stored deployment run logs.
type RunLogFetcher interface {
	FetchRunLogs(ctx context.Context, run *domain.DeploymentRun) (*adapterruntime.RunLogs, error)
}

// SignatureVerifier is the encrypted request contract for artifact signature verification.
type SignatureVerifier interface {
	VerifySignatures(ctx context.Context, artifact *domain.Artifact) ([]domain.ArtifactSignature, error)
}

type secretVersionHistoryLister interface {
	ListVersions(ctx context.Context, secretID uuid.UUID) ([]domain.SecretVersion, error)
}

// RegistryMutationBackend is the ContextVM contract for dashboard registry
// mutations. service.RegistryService and service.RelayFirstRegistry satisfy this
// interface; in relay-first mode the latter preserves publish-OK-before-DB-write
// semantics for service/environment writes.
type RegistryMutationBackend interface {
	CreateService(ctx context.Context, svc *domain.Service) error
	UpdateService(ctx context.Context, svc *domain.Service) error
	UpdateServiceWithExpectedRevision(ctx context.Context, svc *domain.Service, expectedUpdatedAt time.Time) error
	ImportObservedArtifact(ctx context.Context, in service.ImportObservedArtifactInput) (*service.ImportObservedArtifactResult, error)
	DeleteService(ctx context.Context, id uuid.UUID, force bool) error
	CreateEnvironment(ctx context.Context, env *domain.Environment) error
	CreateEnvironmentWithDeploymentUnits(ctx context.Context, env *domain.Environment, units []*domain.DeploymentUnit) error
	GetEnvironment(ctx context.Context, id uuid.UUID) (*domain.Environment, error)
	UpdateEnvironment(ctx context.Context, env *domain.Environment) error
	UpdateEnvironmentWithDeploymentUnits(ctx context.Context, env *domain.Environment, units []*domain.DeploymentUnit, expectedUpdatedAt time.Time) error
	DeleteEnvironment(ctx context.Context, id uuid.UUID, force bool) error
	RegisterArtifact(ctx context.Context, artifact *domain.Artifact) error
}

type EncryptedRouteHandlersConfig struct {
	// IntentProcessor is the Phase 3 dual-dispatch entry point. When non-nil
	// and a domain handler is registered (service, environment), that domain's
	// mutations are routed through ProcessInProcess for shared idempotency (§4.1).
	IntentProcessor *IntentProcessor
	Secrets         repository.SecretRepository
	Encryptor       *secrets.Encryptor
	// SecretPublisher publishes canonical secret records in the legacy path
	// (when the secret domain is not routed through the intent processor).
	SecretPublisher SecretIntentPublisher
	// NotifRepo, NotifPublisher, and NotifNotifier support the notification
	// legacy path (when the notification domain is not intent-enabled).
	NotifRepo       repository.NotificationRepository
	NotifPublisher  NotificationIntentPublisher
	NotifNotifier   NotificationChannelChangeNotifier
	Runs            repository.DeploymentRunRepository
	RunLogs         RunLogFetcher
	Artifacts       repository.ArtifactRepository
	Signatures      repository.ArtifactSignatureRepository
	SignVerifier    SignatureVerifier
	Services        repository.ServiceRepository
	Intents         repository.DeploymentIntentRepository
	Registry        RegistryMutationBackend
	DeploymentUnits readmodel.EnvironmentDeploymentUnitReader
	RBAC            *auth.RBAC
	Logger          *zap.Logger
}

type EncryptedRouteHandlers struct {
	intentProcessor *IntentProcessor
	secrets         repository.SecretRepository
	encryptor       *secrets.Encryptor
	secretPublisher SecretIntentPublisher
	notifRepo       repository.NotificationRepository
	notifPublisher  NotificationIntentPublisher
	notifNotifier   NotificationChannelChangeNotifier
	runs            repository.DeploymentRunRepository
	runLogs         RunLogFetcher
	artifacts       repository.ArtifactRepository
	signatures      repository.ArtifactSignatureRepository
	signVerifier    SignatureVerifier
	services        repository.ServiceRepository
	intents         repository.DeploymentIntentRepository
	registry        RegistryMutationBackend
	deploymentUnits readmodel.EnvironmentDeploymentUnitReader
	rbac            *auth.RBAC
	logger          *zap.Logger
}

// NewEncryptedRouteHandlers adapts sensitive route-only actions onto encrypted
// signer-first encrypted request/result operations. Secrets, stored run logs, and
// signature verification results are never projected to the public sidecar.
func NewEncryptedRouteHandlers(cfg EncryptedRouteHandlersConfig) *EncryptedRouteHandlers {
	logger := cfg.Logger
	if logger == nil {
		logger = zap.NewNop()
	}
	return &EncryptedRouteHandlers{
		intentProcessor: cfg.IntentProcessor,
		secrets:         cfg.Secrets,
		encryptor:       cfg.Encryptor,
		secretPublisher: cfg.SecretPublisher,
		notifRepo:       cfg.NotifRepo,
		notifPublisher:  cfg.NotifPublisher,
		notifNotifier:   cfg.NotifNotifier,
		runs:            cfg.Runs,
		runLogs:         cfg.RunLogs,
		artifacts:       cfg.Artifacts,
		signatures:      cfg.Signatures,
		signVerifier:    cfg.SignVerifier,
		services:        cfg.Services,
		intents:         cfg.Intents,
		registry:        cfg.Registry,
		deploymentUnits: cfg.DeploymentUnits,
		rbac:            cfg.RBAC,
		logger:          logger.Named("encrypted-route-handlers"),
	}
}

func (h *EncryptedRouteHandlers) Register(transport *EncryptedRequestTransport) {
	if h == nil || transport == nil {
		return
	}
	h.registerRouteHandler(transport, EncryptedOperationServiceSecretsList, h.ListSecrets, ContextVMMethodServiceSecretsList)
	h.registerRouteHandler(transport, EncryptedOperationServiceSecretsCreate, h.CreateSecret, ContextVMMethodServiceSecretsCreate)
	h.registerRouteHandler(transport, EncryptedOperationServiceSecretsUpdate, h.UpdateSecret, ContextVMMethodServiceSecretsUpdate)
	h.registerRouteHandler(transport, EncryptedOperationServiceSecretsDelete, h.DeleteSecret, ContextVMMethodServiceSecretsDelete)
	h.registerRouteHandler(transport, EncryptedOperationServiceSecretsReveal, h.RevealSecret, ContextVMMethodServiceSecretsReveal)
	h.registerRouteHandler(transport, EncryptedOperationDeploymentRunLogsGet, h.GetRunLogs, ContextVMMethodDeploymentRunLogsGet)
	h.registerRouteHandler(transport, EncryptedOperationArtifactSignaturesVerify, h.VerifyArtifactSignatures)
	transport.RegisterContextVMHandler(ContextVMMethodServiceCreate, h.CreateService)
	transport.RegisterContextVMHandler(ContextVMMethodServiceUpdate, h.UpdateService)
	transport.RegisterContextVMHandler(ContextVMMethodServiceDelete, h.DeleteService)
	transport.RegisterContextVMHandler(ContextVMMethodEnvironmentCreate, h.CreateEnvironment)
	transport.RegisterContextVMHandler(ContextVMMethodEnvironmentGetDetails, h.GetEnvironmentDetails)
	transport.RegisterContextVMHandler(ContextVMMethodEnvironmentUpdate, h.UpdateEnvironment)
	transport.RegisterContextVMHandler(ContextVMMethodEnvironmentDelete, h.DeleteEnvironment)
	transport.RegisterContextVMHandler(ContextVMMethodArtifactRegister, h.RegisterArtifact)
	transport.RegisterContextVMHandler(ContextVMMethodArtifactImportObserved, h.ImportObservedArtifact)
	h.registerContextVMRouteHandler(transport, EncryptedOperationNotificationChannelsCreate, h.CreateNotificationChannel, ContextVMMethodNotificationChannelCreate, ContextVMMethodNotificationChannelsCreate)
	h.registerContextVMRouteHandler(transport, EncryptedOperationNotificationChannelsUpdate, h.UpdateNotificationChannel, ContextVMMethodNotificationChannelUpdate, ContextVMMethodNotificationChannelsUpdate)
	h.registerContextVMRouteHandler(transport, EncryptedOperationNotificationChannelsDelete, h.DeleteNotificationChannel, ContextVMMethodNotificationChannelDelete, ContextVMMethodNotificationChannelsDelete)
}

// ImportObservedArtifact records an already-running, observation-verified image
// as governed build/artifact lineage so an operator never needs to edit the
// database to bridge missing artifact state. It deliberately leaves desired
// state alone: aligning it stays a separate, reviewed deployment.
func (h *EncryptedRouteHandlers) ImportObservedArtifact(ctx context.Context, request ContextVMRequest) (any, error) {
	if h.registry == nil {
		return nil, fmt.Errorf("artifact registry mutation handling is not configured")
	}
	var payload dto.ImportObservedArtifactRequest
	if err := decodeStrictContextVMParams(request.RPC.Params, &payload); err != nil {
		return nil, err
	}
	if payload.ServiceID == uuid.Nil || payload.EnvironmentID == uuid.Nil {
		return nil, fmt.Errorf("service_id and environment_id are required")
	}
	if payload.DeploymentUnitID != nil && *payload.DeploymentUnitID == uuid.Nil {
		return nil, fmt.Errorf("deployment_unit_id must not be nil")
	}
	authorizer := encryptedTenantAuthorizer{services: h.services, environments: h.registry, rbac: h.rbac}
	// Authorize the environment too: the payload names one, and every other
	// service+environment mutation proves the operator owns both.
	if _, _, err := authorizer.authorizeServiceEnvironment(
		ctx, request.Event, payload.ServiceID, payload.EnvironmentID,
		domain.PermWriteServices, domain.PermWriteServices,
	); err != nil {
		return nil, err
	}
	requestedBy := ""
	if request.Event != nil {
		requestedBy = strings.TrimSpace(request.Event.PubKey.Hex())
	}
	result, err := h.registry.ImportObservedArtifact(ctx, service.ImportObservedArtifactInput{
		ServiceID:        payload.ServiceID,
		EnvironmentID:    payload.EnvironmentID,
		DeploymentUnitID: payload.DeploymentUnitID,
		ImageRepo:        strings.TrimSpace(payload.ImageRepo),
		ImageTag:         strings.TrimSpace(payload.ImageTag),
		ImageDigest:      strings.TrimSpace(payload.ImageDigest),
		GitSHA:           strings.TrimSpace(payload.GitSHA),
		GitRef:           strings.TrimSpace(payload.GitRef),
		RequestedBy:      requestedBy,
	})
	if err != nil {
		return nil, err
	}
	response := map[string]any{
		"status":            result.Status,
		"artifact":          result.Artifact,
		"observed_digest":   result.ObservedDigest,
		"observation_id":    result.ObservationID.String(),
		"registry_verified": result.RegistryVerified,
		"verified_labels":   result.VerifiedLabels,
		"desired_state":     result.DesiredStateNote,
		"idempotency_key":   effectiveIdempotencyKey(request, payload.IdempotencyKey),
	}
	if result.Artifact != nil {
		response["artifact_id"] = result.Artifact.ID.String()
	}
	if result.Build != nil {
		response["build"] = result.Build
		response["build_id"] = result.Build.ID.String()
	}
	return response, nil
}

func (h *EncryptedRouteHandlers) RegisterArtifact(ctx context.Context, request ContextVMRequest) (any, error) {
	if h.registry == nil {
		return nil, fmt.Errorf("artifact registry mutation handling is not configured")
	}
	var payload dto.RegisterArtifactRequest
	if err := decodeStrictContextVMParams(request.RPC.Params, &payload); err != nil {
		return nil, err
	}
	if payload.BuildID == uuid.Nil || payload.ServiceID == uuid.Nil {
		return nil, fmt.Errorf("build_id and service_id are required")
	}
	if strings.TrimSpace(payload.ImageRepo) == "" || strings.TrimSpace(payload.ImageTag) == "" || strings.TrimSpace(payload.ImageDigest) == "" {
		return nil, fmt.Errorf("image_repo, image_tag, and image_digest are required")
	}
	authorizer := encryptedTenantAuthorizer{services: h.services, environments: h.registry, rbac: h.rbac}
	if _, err := authorizer.authorizeService(ctx, request.Event, payload.ServiceID, domain.PermWriteServices); err != nil {
		return nil, err
	}
	scanStatus := domain.ScanStatus(strings.TrimSpace(payload.ScanStatus))
	if scanStatus == "" {
		scanStatus = domain.ScanStatusUnknown
	}
	artifact := &domain.Artifact{
		BuildID: payload.BuildID, ServiceID: payload.ServiceID,
		ImageRepo: strings.TrimSpace(payload.ImageRepo), ImageTag: strings.TrimSpace(payload.ImageTag),
		ImageDigest: strings.TrimSpace(payload.ImageDigest), ManifestMediaType: strings.TrimSpace(payload.ManifestMediaType),
		SizeBytes: payload.SizeBytes, SBOMURL: strings.TrimSpace(payload.SBOMURL), SignatureRef: strings.TrimSpace(payload.SignatureRef),
		ScanStatus: scanStatus, Metadata: payload.Metadata,
	}
	if err := h.registry.RegisterArtifact(ctx, artifact); err != nil {
		return nil, fmt.Errorf("failed to register artifact: %w", err)
	}
	return map[string]any{"status": "registered", "artifact": artifact, "artifact_id": artifact.ID.String()}, nil
}

type encryptedRouteHandler = EncryptedRequestHandler

func (h *EncryptedRouteHandlers) registerRouteHandler(transport *EncryptedRequestTransport, operation string, handler encryptedRouteHandler, contextVMAliases ...string) {
	transport.RegisterHandler(operation, handler)
	register := func(method string) {
		transport.RegisterContextVMHandler(method, func(ctx context.Context, request ContextVMRequest) (any, error) {
			return handler(ctx, EncryptedRequest{Event: request.Event, Envelope: EncryptedRequestEnvelope{Version: ContextVMWireVersion, Operation: operation, RequesterPubkey: request.Event.PubKey.Hex(), Payload: request.RPC.Params}})
		})
	}
	register(operation)
	for _, alias := range contextVMAliases {
		register(alias)
	}
}

// registerContextVMRouteHandler registers a ContextVMHandler under the
// encrypted operation name and all ContextVM method aliases. It mirrors
// registerRouteHandler for handlers already written against ContextVMRequest.
func (h *EncryptedRouteHandlers) registerContextVMRouteHandler(transport *EncryptedRequestTransport, operation string, handler ContextVMHandler, contextVMAliases ...string) {
	transport.RegisterHandler(operation, func(ctx context.Context, req EncryptedRequest) (any, error) {
		return handler(ctx, ContextVMRequest{
			Event: req.Event,
			RPC:   ContextVMJSONRPCRequest{Method: req.Envelope.Operation, Params: req.Envelope.Payload},
		})
	})
	transport.RegisterContextVMHandler(operation, handler)
	for _, alias := range contextVMAliases {
		transport.RegisterContextVMHandler(alias, handler)
	}
}

type encryptedEnvironmentCreatePayload struct {
	// ID is the optional client-minted entity id (see dto.CreateServiceRequest.ID).
	ID                 string                           `json:"id,omitempty"`
	OrgID              uuid.UUID                        `json:"org_id,omitempty"`
	Name               string                           `json:"name"`
	LoomWorkerSelector json.RawMessage                  `json:"loom_worker_selector,omitempty"`
	RuntimeConfig      map[string]any                   `json:"runtime_config,omitempty"`
	Targeting          *dto.EnvironmentTargetingRequest `json:"targeting,omitempty"`
	DeploymentUnits    []dto.DeploymentUnitRequest      `json:"deployment_units,omitempty"`
	ReconcileMode      string                           `json:"reconcile_mode,omitempty"`
	DeployStrategy     string                           `json:"deploy_strategy,omitempty"`
	Protected          bool                             `json:"protected,omitempty"`
}

type encryptedEnvironmentGetDetailsPayload struct {
	ID string `json:"id"`
}

type encryptedEnvironmentUpdatePayload struct {
	ID                 string                           `json:"id"`
	OrgID              *uuid.UUID                       `json:"org_id,omitempty"`
	ExpectedUpdatedAt  *time.Time                       `json:"expected_updated_at,omitempty"`
	Name               string                           `json:"name,omitempty"`
	LoomWorkerSelector json.RawMessage                  `json:"loom_worker_selector,omitempty"`
	RuntimeConfig      map[string]any                   `json:"runtime_config,omitempty"`
	Targeting          *dto.EnvironmentTargetingRequest `json:"targeting,omitempty"`
	DeploymentUnits    []dto.DeploymentUnitRequest      `json:"deployment_units,omitempty"`
	ReconcileMode      string                           `json:"reconcile_mode,omitempty"`
	DeployStrategy     string                           `json:"deploy_strategy,omitempty"`
	Protected          *bool                            `json:"protected,omitempty"`
}

type encryptedEnvironmentDeletePayload struct {
	ID    string `json:"id"`
	Force bool   `json:"force,omitempty"`
}

func supportsManagedRuntimeConfig(runtimeType domain.RuntimeType) bool {
	switch runtimeType {
	case domain.RuntimeTypeDocker, domain.RuntimeTypeCompose:
		return true
	default:
		return false
	}
}

func (h *EncryptedRouteHandlers) authorizeServiceUpdate(ctx context.Context, authorizer encryptedTenantAuthorizer, event *nostr.Event, payload dto.UpdateServiceRequest) (*domain.Service, error) {
	if payload.ID == uuid.Nil {
		return nil, fmt.Errorf("service_id is required")
	}
	if h.services == nil {
		return nil, fmt.Errorf("service repository is not configured")
	}
	svc, err := h.services.GetByID(ctx, payload.ID)
	if err != nil {
		if err == repository.ErrNotFound {
			return nil, fmt.Errorf("service not found")
		}
		return nil, fmt.Errorf("failed to fetch service")
	}
	if svc == nil {
		return nil, fmt.Errorf("service not found")
	}
	if svc.OrgID != uuid.Nil {
		if err := authorizer.authorizeOrg(ctx, event, svc.OrgID, domain.PermWriteServices); err != nil {
			return nil, err
		}
		return svc, nil
	}
	if payload.OrgID == nil || *payload.OrgID == uuid.Nil {
		return nil, fmt.Errorf("organization is required")
	}
	if err := authorizer.authorizeOrg(ctx, event, *payload.OrgID, domain.PermWriteServices); err != nil {
		return nil, err
	}
	return svc, nil
}

func (h *EncryptedRouteHandlers) CreateService(ctx context.Context, request ContextVMRequest) (any, error) {
	if h.registry == nil {
		return nil, fmt.Errorf("service registry mutation handling is not configured")
	}
	var payload dto.CreateServiceRequest
	if err := decodeStrictContextVMParams(request.RPC.Params, &payload); err != nil {
		return nil, err
	}
	name := strings.TrimSpace(payload.Name)
	artifactRepo := strings.TrimSpace(payload.ArtifactRepo)
	if name == "" || artifactRepo == "" {
		return nil, fmt.Errorf("name and artifact_repo are required")
	}
	serviceID, _, err := domain.ResolveCreateEntityID(payload.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	authorizer := encryptedTenantAuthorizer{services: h.services, environments: h.registry, rbac: h.rbac}
	if err := authorizer.authorizeOrg(ctx, request.Event, payload.OrgID, domain.PermWriteServices); err != nil {
		return nil, err
	}
	runtimeType := domain.RuntimeTypeDocker
	if strings.TrimSpace(payload.RuntimeType) != "" {
		runtimeType = domain.RuntimeType(strings.TrimSpace(payload.RuntimeType))
		if err := domain.ValidateRuntimeType(runtimeType); err != nil {
			return nil, fmt.Errorf("invalid runtime_type: %w", err)
		}
	}
	defaultBranch := strings.TrimSpace(payload.DefaultBranch)
	if defaultBranch == "" {
		defaultBranch = "main"
	}
	repositoryRef := repositoryRefFromRequest(payload.Repository)
	repoURL := strings.TrimSpace(payload.RepoURL)
	if repositoryRef != nil && strings.TrimSpace(repositoryRef.CloneURL) != "" {
		repoURL = strings.TrimSpace(repositoryRef.CloneURL)
	}
	svc := &domain.Service{
		ID:            serviceID,
		OrgID:         payload.OrgID,
		Name:          name,
		RepoURL:       repoURL,
		Repository:    repositoryRef,
		ArtifactRepo:  artifactRepo,
		DefaultBranch: defaultBranch,
		RuntimeType:   runtimeType,
	}
	if payload.ManagedRuntimeConfig != nil {
		if !supportsManagedRuntimeConfig(svc.RuntimeType) {
			return nil, fmt.Errorf("managed runtime configuration requires a managed runtime_type")
		}
		managed := domain.NormalizeManagedRuntimeConfig(payload.ManagedRuntimeConfig)
		if err := domain.ValidateManagedRuntimeConfig(managed); err != nil {
			return nil, fmt.Errorf("invalid managed runtime configuration: %w", err)
		}
		if len(managed.SecretRefs) > 0 && h.secrets == nil {
			return nil, fmt.Errorf("secret repository is required to validate managed secret references")
		}
		for _, ref := range managed.SecretRefs {
			secret, err := h.secrets.GetByID(ctx, ref.SecretID)
			if err != nil || secret == nil || secret.ServiceID != svc.ID {
				return nil, fmt.Errorf("managed runtime configuration contains an unavailable secret reference")
			}
		}
		svc.RuntimeConfig = &domain.ServiceRuntimeConfig{Managed: managed}
	}
	// Phase 3 dual dispatch (§4.1): when the service domain is enabled,
	// route through ProcessInProcess for shared idempotency with relay intents.
	if h.serviceIntentEnabled() {
		intent := h.serviceIntentFromContextVM(request, "create", svc, effectiveIdempotencyKey(request, payload.IdempotencyKey))
		if err := h.intentProcessor.ProcessInProcess(ctx, intent); err != nil {
			return nil, fmt.Errorf("failed to create service: %w", err)
		}
		// Read back the service to return the stamped entity.
		created, _ := h.services.GetByID(ctx, svc.ID)
		if created != nil {
			svc = created
		}
	} else if err := h.registry.CreateService(ctx, svc); err != nil {
		return nil, fmt.Errorf("failed to create service: %w", err)
	}
	return map[string]any{"status": "created", "service": svc, "service_id": svc.ID.String(), "idempotency_key": effectiveIdempotencyKey(request, payload.IdempotencyKey)}, nil
}

func (h *EncryptedRouteHandlers) UpdateService(ctx context.Context, request ContextVMRequest) (any, error) {
	if h.registry == nil {
		return nil, fmt.Errorf("service registry mutation handling is not configured")
	}
	var payload dto.UpdateServiceRequest
	if err := decodeStrictContextVMParams(request.RPC.Params, &payload); err != nil {
		return nil, err
	}
	authorizer := encryptedTenantAuthorizer{services: h.services, environments: h.registry, rbac: h.rbac}
	svc, err := h.authorizeServiceUpdate(ctx, authorizer, request.Event, payload)
	if err != nil {
		return nil, err
	}
	if payload.OrgID != nil {
		if *payload.OrgID == uuid.Nil {
			return nil, fmt.Errorf("org_id must not be nil")
		}
		if svc.OrgID != uuid.Nil && svc.OrgID != *payload.OrgID {
			return nil, fmt.Errorf("cannot move service to a different organization")
		}
		svc.OrgID = *payload.OrgID
	}
	if payload.Name != nil {
		name := strings.TrimSpace(*payload.Name)
		if name == "" {
			return nil, fmt.Errorf("name must not be empty")
		}
		svc.Name = name
	}
	if payload.RepoURL != nil {
		svc.RepoURL = strings.TrimSpace(*payload.RepoURL)
		if svc.Repository != nil {
			svc.Repository.CloneURL = svc.RepoURL
		}
	}
	if payload.Repository != nil {
		svc.Repository = repositoryRefFromRequest(payload.Repository)
		if svc.Repository != nil && strings.TrimSpace(svc.Repository.CloneURL) != "" {
			svc.RepoURL = strings.TrimSpace(svc.Repository.CloneURL)
		}
	}
	if payload.ArtifactRepo != nil {
		artifactRepo := strings.TrimSpace(*payload.ArtifactRepo)
		if artifactRepo == "" {
			return nil, fmt.Errorf("artifact_repo must not be empty")
		}
		svc.ArtifactRepo = artifactRepo
	}
	if payload.DefaultBranch != nil {
		branch := strings.TrimSpace(*payload.DefaultBranch)
		if branch == "" {
			return nil, fmt.Errorf("default_branch must not be empty")
		}
		svc.DefaultBranch = branch
	}
	if payload.RuntimeType != nil {
		runtimeType := domain.RuntimeType(strings.TrimSpace(*payload.RuntimeType))
		if err := domain.ValidateRuntimeType(runtimeType); err != nil {
			return nil, fmt.Errorf("invalid runtime_type: %w", err)
		}
		svc.RuntimeType = runtimeType
	}
	if !supportsManagedRuntimeConfig(svc.RuntimeType) && svc.RuntimeConfig != nil && svc.RuntimeConfig.Managed != nil && payload.ManagedRuntimeConfig == nil {
		return nil, fmt.Errorf("cannot change a service with managed runtime configuration to an unmanaged runtime_type")
	}
	if payload.ManagedRuntimeConfig != nil {
		if !supportsManagedRuntimeConfig(svc.RuntimeType) {
			return nil, fmt.Errorf("managed runtime configuration requires a managed runtime_type")
		}
		managed := domain.NormalizeManagedRuntimeConfig(payload.ManagedRuntimeConfig)
		if err := domain.ValidateManagedRuntimeConfig(managed); err != nil {
			return nil, fmt.Errorf("invalid managed runtime configuration: %w", err)
		}
		if len(managed.SecretRefs) > 0 && h.secrets == nil {
			return nil, fmt.Errorf("secret repository is required to validate managed secret references")
		}
		for _, ref := range managed.SecretRefs {
			secret, err := h.secrets.GetByID(ctx, ref.SecretID)
			if err != nil || secret == nil || secret.ServiceID != svc.ID {
				return nil, fmt.Errorf("managed runtime configuration contains an unavailable secret reference")
			}
		}
		if svc.RuntimeConfig == nil {
			svc.RuntimeConfig = &domain.ServiceRuntimeConfig{}
		}
		svc.RuntimeConfig.Managed = managed
	}
	if payload.AdoptedPublicEnvironment != nil {
		if svc.RuntimeConfig == nil || svc.RuntimeConfig.Adopted == nil {
			return nil, fmt.Errorf("adopted_public_environment requires an already-adopted service")
		}
		if svc.RuntimeConfig.Adopted.Environment == nil {
			svc.RuntimeConfig.Adopted.Environment = map[string]string{}
		}
		for key, value := range payload.AdoptedPublicEnvironment {
			key = strings.TrimSpace(key)
			if !strings.HasPrefix(key, "PUBLIC_") {
				return nil, fmt.Errorf("adopted public environment key %q must use the PUBLIC_ prefix", key)
			}
			svc.RuntimeConfig.Adopted.Environment[key] = value
		}
	}
	// Phase 3 dual dispatch (§4.1): when the service domain is enabled,
	// route through ProcessInProcess for shared idempotency with relay intents.
	if h.serviceIntentEnabled() {
		intent := h.serviceIntentFromContextVM(request, "update", svc, effectiveIdempotencyKey(request, payload.IdempotencyKey))
		if payload.ExpectedUpdatedAt != nil && !payload.ExpectedUpdatedAt.IsZero() {
			ts := payload.ExpectedUpdatedAt.Format(time.RFC3339Nano)
			intent.Content["expected_updated_at"] = ts
			epoch := payload.ExpectedUpdatedAt.UnixNano()
			intent.ExpectedUpdatedAt = &epoch
		}
		if err := h.intentProcessor.ProcessInProcess(ctx, intent); err != nil {
			return nil, fmt.Errorf("failed to update service: %w", err)
		}
		updated, _ := h.services.GetByID(ctx, svc.ID)
		if updated != nil {
			svc = updated
		}
	} else if payload.ExpectedUpdatedAt != nil && !payload.ExpectedUpdatedAt.IsZero() {
		if err := h.registry.UpdateServiceWithExpectedRevision(ctx, svc, *payload.ExpectedUpdatedAt); err != nil {
			return nil, fmt.Errorf("failed to update service: %w", err)
		}
	} else if err := h.registry.UpdateService(ctx, svc); err != nil {
		return nil, fmt.Errorf("failed to update service: %w", err)
	}
	return map[string]any{"status": "updated", "service": svc, "service_id": svc.ID.String(), "idempotency_key": effectiveIdempotencyKey(request, payload.IdempotencyKey)}, nil
}

func (h *EncryptedRouteHandlers) DeleteService(ctx context.Context, request ContextVMRequest) (any, error) {
	if h.registry == nil {
		return nil, fmt.Errorf("service registry mutation handling is not configured")
	}
	var payload dto.DeleteServiceRequest
	if err := decodeStrictContextVMParams(request.RPC.Params, &payload); err != nil {
		return nil, err
	}
	authorizer := encryptedTenantAuthorizer{services: h.services, environments: h.registry, rbac: h.rbac}
	if _, err := authorizer.authorizeService(ctx, request.Event, payload.ID, domain.PermWriteServices); err != nil {
		return nil, err
	}
	// Phase 3 dual dispatch (§4.1): when the service domain is enabled,
	// route through ProcessInProcess for shared idempotency with relay intents.
	if h.serviceIntentEnabled() {
		intent := h.serviceIntentFromContextVM(request, "delete", &domain.Service{ID: payload.ID}, effectiveIdempotencyKey(request, payload.IdempotencyKey))
		intent.Content["deleted"] = true
		intent.Content["force"] = payload.Force
		if err := h.intentProcessor.ProcessInProcess(ctx, intent); err != nil {
			return nil, fmt.Errorf("failed to delete service: %w", err)
		}
	} else if err := h.registry.DeleteService(ctx, payload.ID, payload.Force); err != nil {
		return nil, fmt.Errorf("failed to delete service: %w", err)
	}
	return map[string]any{"status": "deleted", "service_id": payload.ID.String(), "idempotency_key": effectiveIdempotencyKey(request, payload.IdempotencyKey)}, nil
}

// serviceIntentFromContextVM builds a synthetic Intent for the dual-dispatch
// path (§4.1). The ContextVM handler has already authorized the request; the
// intent processor shares the same idempotency store as the relay path.
func (h *EncryptedRouteHandlers) serviceIntentFromContextVM(request ContextVMRequest, op string, svc *domain.Service, idempotencyKey string) *Intent {
	content := map[string]interface{}{
		"id":             svc.ID.String(),
		"name":           svc.Name,
		"repo_url":       svc.RepoURL,
		"artifact_repo":  svc.ArtifactRepo,
		"default_branch": svc.DefaultBranch,
		"runtime_type":   string(svc.RuntimeType),
		"org_id":         svc.OrgID.String(),
	}
	if svc.Repository != nil {
		content["repository"] = svc.Repository
	}

	intentID := idempotencyKey
	if intentID == "" {
		intentID = domain.NewEntityID().String()
	}

	actor := ""
	if request.Event != nil {
		actor = request.Event.PubKey.Hex()
	}

	return &Intent{
		Domain:     "service",
		Op:         op,
		OrgID:      svc.OrgID,
		IntentID:   intentID,
		Coordinate: svc.ID.String(),
		Content:    content,
		Actor:      actor,
	}
}

// serviceIntentEnabled reports whether the service domain is routed through
// the intent processor (Phase 3 dual dispatch).
func (h *EncryptedRouteHandlers) serviceIntentEnabled() bool {
	return h.intentProcessor != nil && h.intentProcessor.Handler("service") != nil
}

// secretIntentEnabled reports whether the secret domain is routed through
// the intent processor (Phase 3 N1 dual dispatch).
func (h *EncryptedRouteHandlers) secretIntentEnabled() bool {
	return h.intentProcessor != nil && h.intentProcessor.Handler("secret") != nil
}

// notificationIntentEnabled reports whether the notification domain is routed through
// the intent processor (Phase 3 N1 dual dispatch).
func (h *EncryptedRouteHandlers) notificationIntentEnabled() bool {
	return h.intentProcessor != nil && h.intentProcessor.Handler("notification") != nil
}

// resolveSecretOrgID resolves the org_id for a secret from its parent service.
func (h *EncryptedRouteHandlers) resolveSecretOrgID(ctx context.Context, serviceID uuid.UUID) uuid.UUID {
	if h.services != nil {
		if svc, err := h.services.GetByID(ctx, serviceID); err == nil && svc != nil {
			return svc.OrgID
		}
	}
	return uuid.Nil
}

func repositoryRefFromRequest(request *dto.RepositoryRefRequest) *domain.RepositoryRef {
	if request == nil {
		return nil
	}
	ref := &domain.RepositoryRef{
		Source:         strings.TrimSpace(request.Source),
		RepoCoordinate: strings.TrimSpace(request.RepoCoordinate),
		CloneURL:       strings.TrimSpace(request.CloneURL),
		WebURL:         strings.TrimSpace(request.WebURL),
		RelayURLs:      append([]string(nil), request.RelayURLs...),
	}
	if request.CI != nil {
		ref.CI = &domain.ServiceCIConfig{Provider: strings.TrimSpace(request.CI.Provider), WorkflowPath: strings.TrimSpace(request.CI.WorkflowPath)}
	}
	return ref
}

func effectiveIdempotencyKey(request ContextVMRequest, compatibilityKey string) string {
	if token := strings.TrimSpace(request.ProgressToken); token != "" {
		return token
	}
	return strings.TrimSpace(compatibilityKey)
}

// environmentDualDispatch routes an environment mutation through the intent
// processor when the environment domain is enabled. The ContextVM authorization
// has already been checked by the caller. Returns (result, true, nil) if
// dual dispatch handled the request, or (nil, false, nil) to fall through to
// the legacy path.
func (h *EncryptedRouteHandlers) environmentDualDispatch(ctx context.Context, request ContextVMRequest, op string, envID uuid.UUID, orgID uuid.UUID, content map[string]interface{}) error {
	if h.intentProcessor == nil {
		return nil
	}
	if h.intentProcessor.Handler("environment") == nil {
		return nil
	}
	intent := &Intent{
		Domain:     "environment",
		Op:         op,
		OrgID:      orgID,
		IntentID:   effectiveIdempotencyKey(request, envID.String()),
		Coordinate: envID.String(),
		Content:    content,
		Actor:      request.Event.PubKey.Hex(),
	}
	// Check for expected_updated_at in content.
	if raw, ok := content["expected_updated_at"]; ok {
		switch v := raw.(type) {
		case float64:
			ts := int64(v)
			intent.ExpectedUpdatedAt = &ts
		case int64:
			intent.ExpectedUpdatedAt = &v
		}
	}
	return h.intentProcessor.ProcessInProcess(ctx, intent)
}

// buildEnvironmentIntentContent builds the intent content map from a parsed
// domain.Environment and optional deployment units. Returns nil if the
// environment domain is not enabled in the intent processor (legacy path).
func (h *EncryptedRouteHandlers) buildEnvironmentIntentContent(env *domain.Environment, units []*domain.DeploymentUnit) map[string]interface{} {
	if h.intentProcessor == nil || h.intentProcessor.Handler("environment") == nil {
		return nil
	}
	content := map[string]interface{}{
		"id":              env.ID.String(),
		"name":            env.Name,
		"deploy_strategy": string(env.DeployStrategy),
		"protected":       env.Protected,
	}
	if env.OrgID != uuid.Nil {
		content["org_id"] = env.OrgID.String()
	}
	if env.LoomWorkerSelector != nil {
		content["loom_worker_selector"] = env.LoomWorkerSelector
	}
	if env.RuntimeConfig != nil {
		content["runtime_config"] = env.RuntimeConfig
	}
	content["targeting"] = map[string]interface{}{
		"default_unit_key":       env.Targeting.DefaultUnitKey,
		"failure_domain_labels":  env.Targeting.FailureDomainLabels,
		"secret_scope_mode":      string(env.Targeting.SecretScopeMode),
		"default_reconcile_mode": string(env.Targeting.DefaultReconcileMode),
	}
	if units != nil {
		unitMaps := make([]map[string]interface{}, 0, len(units))
		for _, u := range units {
			um := map[string]interface{}{
				"key":          u.Key,
				"runtime_type": string(u.RuntimeType),
			}
			if u.DisplayName != "" {
				um["display_name"] = u.DisplayName
			}
			if u.EndpointRef != "" {
				um["endpoint_ref"] = u.EndpointRef
			}
			if u.ComposeDir != "" {
				um["compose_dir"] = u.ComposeDir
			}
			if u.Namespace != "" {
				um["namespace"] = u.Namespace
			}
			if len(u.NetworkProfile) > 0 {
				um["network_profile"] = u.NetworkProfile
			}
			if u.GitSource != nil {
				um["git_source"] = map[string]interface{}{
					"repository_url": u.GitSource.RepositoryURL,
					"ref":            u.GitSource.Ref,
					"branch":         u.GitSource.Branch,
					"commit_sha":     u.GitSource.CommitSHA,
				}
			}
			if string(u.ReconcileMode) != "" {
				um["reconcile_mode"] = string(u.ReconcileMode)
			}
			if string(u.OwnershipMode) != "" {
				um["ownership_mode"] = string(u.OwnershipMode)
			}
			if len(u.RuntimeConfig) > 0 {
				um["runtime_config"] = u.RuntimeConfig
			}
			unitMaps = append(unitMaps, um)
		}
		content["deployment_units"] = unitMaps
	}
	return content
}

func (h *EncryptedRouteHandlers) CreateEnvironment(ctx context.Context, request ContextVMRequest) (any, error) {
	if h.registry == nil {
		return nil, fmt.Errorf("environment registry mutation handling is not configured")
	}
	var payload encryptedEnvironmentCreatePayload
	if err := decodeStrictContextVMParams(request.RPC.Params, &payload); err != nil {
		return nil, err
	}
	name := strings.TrimSpace(payload.Name)
	if name == "" {
		return nil, fmt.Errorf("name is required")
	}
	if payload.OrgID == uuid.Nil {
		return nil, fmt.Errorf("org_id is required")
	}
	environmentID, _, err := domain.ResolveCreateEntityID(payload.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	deployStrategy := domain.DeployStrategyReplace
	if strings.TrimSpace(payload.DeployStrategy) != "" {
		deployStrategy = domain.DeployStrategy(strings.TrimSpace(payload.DeployStrategy))
		if err := domain.ValidateDeployStrategy(deployStrategy); err != nil {
			return nil, fmt.Errorf("invalid deploy_strategy: %w", err)
		}
	}
	var selector map[string]any
	if payload.LoomWorkerSelector != nil {
		parsed, err := parseLoomWorkerSelector(payload.LoomWorkerSelector)
		if err != nil {
			return nil, err
		}
		selector = parsed
	}
	env := &domain.Environment{
		ID:                 environmentID,
		OrgID:              payload.OrgID,
		Name:               name,
		LoomWorkerSelector: selector,
		RuntimeConfig:      payload.RuntimeConfig,
		Targeting:          environmentTargetingFromRequest(payload.Targeting),
		DeployStrategy:     deployStrategy,
		Protected:          payload.Protected,
	}
	if err := applyEnvironmentReconcileMode(env, payload.ReconcileMode); err != nil {
		return nil, err
	}
	units, err := deploymentUnitsFromRequests(env, payload.DeploymentUnits)
	if err != nil {
		return nil, err
	}
	if err := h.authorizeEnvironmentOrg(ctx, request, env.OrgID); err != nil {
		return nil, err
	}
	// Phase 3 F3 dual dispatch: route through intent processor when enabled.
	if ddContent := h.buildEnvironmentIntentContent(env, units); ddContent != nil {
		if err := h.environmentDualDispatch(ctx, request, "create", env.ID, env.OrgID, ddContent); err != nil {
			return nil, fmt.Errorf("failed to create environment: %w", err)
		}
		return map[string]any{"status": "created", "environment": env, "environment_id": env.ID.String(), "deployment_units": units}, nil
	}
	if payload.DeploymentUnits != nil {
		if err := h.registry.CreateEnvironmentWithDeploymentUnits(ctx, env, units); err != nil {
			return nil, fmt.Errorf("failed to create environment: %w", err)
		}
	} else if err := h.registry.CreateEnvironment(ctx, env); err != nil {
		return nil, fmt.Errorf("failed to create environment: %w", err)
	}
	return map[string]any{"status": "created", "environment": env, "environment_id": env.ID.String(), "deployment_units": units}, nil
}

func (h *EncryptedRouteHandlers) GetEnvironmentDetails(ctx context.Context, request ContextVMRequest) (any, error) {
	var payload encryptedEnvironmentGetDetailsPayload
	if err := decodeStrictContextVMParams(request.RPC.Params, &payload); err != nil {
		return nil, err
	}
	id, err := parseEncryptedUUID(payload.ID, "environment ID")
	if err != nil {
		return nil, err
	}
	authorizer := encryptedTenantAuthorizer{services: h.services, environments: h.registry, rbac: h.rbac}
	env, err := authorizer.authorizeEnvironment(ctx, request.Event, id, domain.PermReadEnvironments)
	if err != nil {
		return nil, err
	}
	response, err := readmodel.EnvironmentResponse(ctx, env, h.deploymentUnits)
	if err != nil {
		return nil, err
	}
	return response, nil
}

func (h *EncryptedRouteHandlers) UpdateEnvironment(ctx context.Context, request ContextVMRequest) (any, error) {
	if h.registry == nil {
		return nil, fmt.Errorf("environment registry mutation handling is not configured")
	}
	var payload encryptedEnvironmentUpdatePayload
	if err := decodeStrictContextVMParams(request.RPC.Params, &payload); err != nil {
		return nil, err
	}
	id, err := parseEncryptedUUID(payload.ID, "environment ID")
	if err != nil {
		return nil, err
	}
	env, err := h.registry.GetEnvironment(ctx, id)
	if err != nil {
		if err == repository.ErrNotFound {
			return nil, fmt.Errorf("environment not found")
		}
		return nil, fmt.Errorf("failed to fetch environment")
	}
	if env == nil {
		return nil, fmt.Errorf("environment not found")
	}
	if err := h.authorizeEnvironmentOrg(ctx, request, env.OrgID); err != nil {
		return nil, err
	}
	if payload.OrgID != nil {
		if *payload.OrgID == uuid.Nil {
			return nil, fmt.Errorf("org_id must not be nil")
		}
		if *payload.OrgID != env.OrgID {
			if err := h.authorizeEnvironmentOrg(ctx, request, *payload.OrgID); err != nil {
				return nil, err
			}
			env.OrgID = *payload.OrgID
		}
	}
	if strings.TrimSpace(payload.Name) != "" {
		env.Name = strings.TrimSpace(payload.Name)
	}
	if payload.LoomWorkerSelector != nil {
		selector, err := parseLoomWorkerSelector(payload.LoomWorkerSelector)
		if err != nil {
			return nil, err
		}
		env.LoomWorkerSelector = selector
	}
	if payload.RuntimeConfig != nil {
		env.RuntimeConfig = payload.RuntimeConfig
	}
	if payload.Targeting != nil {
		env.Targeting = environmentTargetingFromRequest(payload.Targeting)
	}
	if err := applyEnvironmentReconcileMode(env, payload.ReconcileMode); err != nil {
		return nil, err
	}
	if strings.TrimSpace(payload.DeployStrategy) != "" {
		strategy := domain.DeployStrategy(strings.TrimSpace(payload.DeployStrategy))
		if err := domain.ValidateDeployStrategy(strategy); err != nil {
			return nil, fmt.Errorf("invalid deploy_strategy: %w", err)
		}
		env.DeployStrategy = strategy
	}
	if payload.Protected != nil {
		env.Protected = *payload.Protected
	}
	units, err := deploymentUnitsFromRequests(env, payload.DeploymentUnits)
	if err != nil {
		return nil, err
	}
	// Phase 3 F3 dual dispatch: route through intent processor when enabled.
	if ddContent := h.buildEnvironmentIntentContent(env, units); ddContent != nil {
		if payload.ExpectedUpdatedAt != nil && !payload.ExpectedUpdatedAt.IsZero() {
			ddContent["expected_updated_at"] = payload.ExpectedUpdatedAt.UnixMicro()
		}
		if err := h.environmentDualDispatch(ctx, request, "update", env.ID, env.OrgID, ddContent); err != nil {
			return nil, fmt.Errorf("failed to update environment: %w", err)
		}
		return map[string]any{"status": "updated", "environment": env, "environment_id": env.ID.String(), "deployment_units": units}, nil
	}
	if payload.DeploymentUnits != nil {
		if payload.ExpectedUpdatedAt == nil || payload.ExpectedUpdatedAt.IsZero() {
			return nil, fmt.Errorf("expected_updated_at is required when deployment_units is supplied")
		}
		if err := h.registry.UpdateEnvironmentWithDeploymentUnits(ctx, env, units, *payload.ExpectedUpdatedAt); err != nil {
			return nil, fmt.Errorf("failed to update environment: %w", err)
		}
	} else if err := h.registry.UpdateEnvironment(ctx, env); err != nil {
		return nil, fmt.Errorf("failed to update environment: %w", err)
	}
	return map[string]any{"status": "updated", "environment": env, "environment_id": env.ID.String(), "deployment_units": units}, nil
}

func (h *EncryptedRouteHandlers) DeleteEnvironment(ctx context.Context, request ContextVMRequest) (any, error) {
	if h.registry == nil {
		return nil, fmt.Errorf("environment registry mutation handling is not configured")
	}
	var payload encryptedEnvironmentDeletePayload
	if err := decodeStrictContextVMParams(request.RPC.Params, &payload); err != nil {
		return nil, err
	}
	id, err := parseEncryptedUUID(payload.ID, "environment ID")
	if err != nil {
		return nil, err
	}
	authorizer := encryptedTenantAuthorizer{services: h.services, environments: h.registry, rbac: h.rbac}
	env, err := authorizer.authorizeEnvironment(ctx, request.Event, id, domain.PermWriteEnvironments)
	if err != nil {
		return nil, err
	}
	// Phase 3 F3 dual dispatch: route through intent processor when enabled.
	if h.intentProcessor != nil && h.intentProcessor.Handler("environment") != nil {
		orgID := uuid.Nil
		if env != nil {
			orgID = env.OrgID
		}
		ddContent := map[string]interface{}{
			"id":      id.String(),
			"deleted": true,
			"force":   payload.Force,
		}
		if err := h.environmentDualDispatch(ctx, request, "delete", id, orgID, ddContent); err != nil {
			return nil, fmt.Errorf("failed to delete environment: %w", err)
		}
		return map[string]any{"status": "deleted", "environment_id": id.String()}, nil
	}
	if err := h.registry.DeleteEnvironment(ctx, id, payload.Force); err != nil {
		return nil, fmt.Errorf("failed to delete environment: %w", err)
	}
	return map[string]any{"status": "deleted", "environment_id": id.String()}, nil
}

func decodeStrictContextVMParams(params json.RawMessage, out any) error {
	if len(params) == 0 || string(params) == "null" {
		params = []byte(`{}`)
	}
	var envelope map[string]json.RawMessage
	if err := json.Unmarshal(params, &envelope); err != nil {
		return fmt.Errorf("invalid environment params: %w", err)
	}
	delete(envelope, "_meta")
	businessParams, err := json.Marshal(envelope)
	if err != nil {
		return fmt.Errorf("invalid environment params: %w", err)
	}
	decoder := json.NewDecoder(bytes.NewReader(businessParams))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(out); err != nil {
		return fmt.Errorf("invalid environment params: %w", err)
	}
	if err := decoder.Decode(&struct{}{}); err != io.EOF {
		if err == nil {
			return fmt.Errorf("invalid environment params: multiple JSON values")
		}
		return fmt.Errorf("invalid environment params: %w", err)
	}
	return nil
}

func environmentTargetingFromRequest(request *dto.EnvironmentTargetingRequest) domain.EnvironmentTargeting {
	if request == nil {
		return domain.EnvironmentTargeting{}
	}
	return domain.EnvironmentTargeting{
		DefaultUnitKey:       strings.TrimSpace(request.DefaultUnitKey),
		FailureDomainLabels:  request.FailureDomainLabels,
		SecretScopeMode:      domain.SecretScopeMode(strings.TrimSpace(request.SecretScopeMode)),
		DefaultReconcileMode: domain.ReconcileMode(strings.TrimSpace(request.DefaultReconcileMode)),
	}
}

func applyEnvironmentReconcileMode(env *domain.Environment, value string) error {
	if env == nil {
		return fmt.Errorf("environment is nil")
	}
	mode := domain.ReconcileMode(strings.TrimSpace(value))
	if err := domain.ValidateReconcileMode(mode); err != nil {
		return fmt.Errorf("invalid reconcile_mode: %w", err)
	}
	if mode != "" {
		env.Targeting.DefaultReconcileMode = mode
	}
	domain.NormalizeEnvironmentTargeting(env)
	if err := domain.ValidateReconcileMode(env.Targeting.DefaultReconcileMode); err != nil {
		return fmt.Errorf("invalid targeting.default_reconcile_mode: %w", err)
	}
	switch env.Targeting.SecretScopeMode {
	case "", domain.SecretScopeModeService, domain.SecretScopeModeEnvironment, domain.SecretScopeModeUnit:
	default:
		return fmt.Errorf("invalid targeting.secret_scope_mode %q (allowed: service, environment, unit)", env.Targeting.SecretScopeMode)
	}
	return nil
}

func deploymentUnitsFromRequests(env *domain.Environment, requests []dto.DeploymentUnitRequest) ([]*domain.DeploymentUnit, error) {
	if requests == nil {
		return nil, nil
	}
	defaultRuntime := domain.RuntimeTypeFromRuntimeConfig(env.RuntimeConfig)
	if defaultRuntime == "" {
		defaultRuntime = domain.RuntimeTypeDocker
	}
	units := make([]*domain.DeploymentUnit, 0, len(requests))
	keys := make(map[string]struct{}, len(requests))
	for _, request := range requests {
		unit := &domain.DeploymentUnit{
			ID:             uuid.New(),
			EnvironmentID:  env.ID,
			Key:            strings.TrimSpace(request.Key),
			DisplayName:    strings.TrimSpace(request.DisplayName),
			RuntimeType:    domain.RuntimeType(strings.TrimSpace(request.RuntimeType)),
			EndpointRef:    strings.TrimSpace(request.EndpointRef),
			ComposeDir:     strings.TrimSpace(request.ComposeDir),
			Namespace:      strings.TrimSpace(request.Namespace),
			NetworkProfile: request.NetworkProfile,
			GitSource:      gitSourceBindingFromRequest(request.GitSource),
			ReconcileMode:  domain.ReconcileMode(strings.TrimSpace(request.ReconcileMode)),
			OwnershipMode:  domain.OwnershipMode(strings.TrimSpace(request.OwnershipMode)),
			RuntimeConfig:  request.RuntimeConfig,
		}
		if unit.RuntimeType == "" {
			unit.RuntimeType = defaultRuntime
		}
		if unit.ReconcileMode == "" {
			unit.ReconcileMode = env.Targeting.DefaultReconcileMode
		}
		domain.NormalizeDeploymentUnitTargeting(unit)
		if err := domain.ValidateDeploymentUnit(unit); err != nil {
			return nil, fmt.Errorf("invalid deployment unit %q: %w", unit.Key, err)
		}
		if _, duplicate := keys[unit.Key]; duplicate {
			return nil, fmt.Errorf("duplicate deployment unit key %q", unit.Key)
		}
		keys[unit.Key] = struct{}{}
		units = append(units, unit)
	}
	if len(units) > 0 {
		if _, ok := keys[env.Targeting.DefaultUnitKey]; !ok {
			return nil, fmt.Errorf("targeting.default_unit_key %q does not identify a deployment unit", env.Targeting.DefaultUnitKey)
		}
	}
	return units, nil
}

func gitSourceBindingFromRequest(request *dto.GitSourceRequest) *domain.GitSourceBinding {
	if request == nil {
		return nil
	}
	return &domain.GitSourceBinding{
		RepositoryURL: strings.TrimSpace(request.RepositoryURL),
		Ref:           strings.TrimSpace(request.Ref),
		Branch:        strings.TrimSpace(request.Branch),
		CommitSHA:     strings.TrimSpace(request.CommitSHA),
	}
}

func (h *EncryptedRouteHandlers) authorizeEnvironmentOrg(ctx context.Context, request ContextVMRequest, orgID uuid.UUID) error {
	if orgID == uuid.Nil {
		return fmt.Errorf("environment organization is required")
	}
	if h.rbac == nil {
		return fmt.Errorf("environment RBAC is not configured")
	}
	if request.Event == nil {
		return fmt.Errorf("signed environment request event is required")
	}
	return h.rbac.CheckPermission(ctx, requestPrincipal(EncryptedRequest{Event: request.Event}), orgID, domain.PermWriteEnvironments)
}

func parseLoomWorkerSelector(raw json.RawMessage) (map[string]any, error) {
	trimmed := strings.TrimSpace(string(raw))
	if trimmed == "" || trimmed == "null" {
		return nil, nil
	}
	if strings.HasPrefix(trimmed, "{") {
		var selector map[string]any
		if err := json.Unmarshal(raw, &selector); err != nil {
			return nil, fmt.Errorf("invalid loom_worker_selector object: %w", err)
		}
		return selector, nil
	}
	var text string
	if err := json.Unmarshal(raw, &text); err != nil {
		return nil, fmt.Errorf("loom_worker_selector must be an object or string")
	}
	text = strings.TrimSpace(text)
	if text == "" {
		return map[string]any{}, nil
	}
	selector := map[string]any{}
	parts := strings.FieldsFunc(text, func(r rune) bool { return r == ',' || r == '\n' })
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		key, value, ok := strings.Cut(part, "=")
		if !ok {
			selector["pubkey"] = part
			continue
		}
		key = strings.TrimSpace(key)
		value = strings.TrimSpace(value)
		if key == "" {
			return nil, fmt.Errorf("loom_worker_selector contains an empty key")
		}
		selector[key] = value
	}
	return selector, nil
}

type encryptedSecretPayload struct {
	ServiceID        string `json:"service_id"`
	SecretID         string `json:"secret_id,omitempty"`
	Name             string `json:"name,omitempty"`
	Value            string `json:"value,omitempty"`
	EnvironmentID    string `json:"environment_id,omitempty"`
	EncryptedValue   string `json:"encrypted_value,omitempty"`
	EncryptionMethod string `json:"encryption_method,omitempty"`
}

func (h *EncryptedRouteHandlers) requireSecretDeps() error {
	if h.secrets == nil || h.encryptor == nil {
		return fmt.Errorf("encrypted secret request handling is not configured")
	}
	return nil
}

func (h *EncryptedRouteHandlers) ListSecrets(ctx context.Context, request EncryptedRequest) (any, error) {
	if err := h.requireSecretDeps(); err != nil {
		return nil, err
	}
	var payload encryptedSecretPayload
	if err := decodeEncryptedPayload(request, &payload); err != nil {
		return nil, err
	}
	serviceID, err := parseEncryptedUUID(payload.ServiceID, "service ID")
	if err != nil {
		return nil, err
	}
	if err := h.authorizeServicePermission(ctx, request, serviceID, domain.PermReadSecrets); err != nil {
		return nil, err
	}
	secrets, err := h.secrets.ListByService(ctx, serviceID)
	if err != nil {
		return nil, fmt.Errorf("failed to list secrets")
	}
	refs := make([]domain.SecretRef, 0, len(secrets))
	for i := range secrets {
		refs = append(refs, secrets[i].ToRef())
	}
	return map[string]any{"secrets": refs, "total": len(refs)}, nil
}

func (h *EncryptedRouteHandlers) CreateSecret(ctx context.Context, request EncryptedRequest) (any, error) {
	if err := h.requireSecretDeps(); err != nil {
		return nil, err
	}
	var payload encryptedSecretPayload
	if err := decodeEncryptedPayload(request, &payload); err != nil {
		return nil, err
	}
	serviceID, err := parseEncryptedUUID(payload.ServiceID, "service ID")
	if err != nil {
		return nil, err
	}
	if err := h.authorizeServicePermission(ctx, request, serviceID, domain.PermWriteSecrets); err != nil {
		return nil, err
	}
	name := strings.TrimSpace(payload.Name)
	if name == "" {
		return nil, fmt.Errorf("name is required")
	}
	if payload.Value == "" && payload.EncryptedValue == "" {
		return nil, fmt.Errorf("value is required (either value or encrypted_value)")
	}
	method, err := parseSecretEncryptionMethod(payload.EncryptionMethod, domain.EncryptionNIP44)
	if err != nil {
		return nil, err
	}
	var encrypted []byte
	if payload.EncryptedValue != "" {
		// Client-side NIP-44 encryption: use pre-encrypted value as-is.
		encrypted = []byte(payload.EncryptedValue)
	} else {
		encrypted, err = h.encryptor.Encrypt(payload.Value, method)
		if err != nil {
			return nil, fmt.Errorf("failed to encrypt secret")
		}
	}
	now := time.Now().UTC()
	secret := &domain.ServiceSecret{
		ID:               uuid.New(),
		ServiceID:        serviceID,
		Name:             name,
		EncryptedValue:   encrypted,
		EncryptionMethod: method,
		Version:          1,
		CreatedBy:        normalizeEncryptedPubkey(request.Event.PubKey.Hex()),
		CreatedAt:        now,
		UpdatedAt:        now,
	}
	if strings.TrimSpace(payload.EnvironmentID) != "" {
		envID, err := parseEncryptedUUID(payload.EnvironmentID, "environment ID")
		if err != nil {
			return nil, err
		}
		secret.EnvironmentID = &envID
	}
	// Phase 3 N1 dual dispatch (§4.1): when the secret domain is enabled,
	// route through ProcessInProcess for shared idempotency with relay intents.
	if h.secretIntentEnabled() {
		content := BuildSecretIntentContent(serviceID, secret.ID, name, payload.Value, secret.EnvironmentID, method)
		if payload.EncryptedValue != "" {
			content["encrypted_value"] = payload.EncryptedValue
			delete(content, "value") // Don't pass plaintext when client pre-encrypted.
		}
		intent := &Intent{
			Domain:     "secret",
			Op:         "create",
			OrgID:      h.resolveSecretOrgID(ctx, serviceID),
			IntentID:   uuid.New().String(),
			Coordinate: secret.ID.String(),
			Content:    content,
			Actor:      normalizeEncryptedPubkey(request.Event.PubKey.Hex()),
		}
		if err := h.intentProcessor.ProcessInProcess(ctx, intent); err != nil {
			return nil, fmt.Errorf("failed to create secret: %w", err)
		}
		// Read back to return stamped entity.
		if created, _ := h.secrets.GetByID(ctx, secret.ID); created != nil {
			secret = created
		}
	} else {
		if err := h.secrets.Create(ctx, secret); err != nil {
			return nil, fmt.Errorf("failed to create secret")
		}
		// Legacy path: publish canonical record so relay state stays current.
		if h.secretPublisher != nil {
			if pubErr := h.secretPublisher.PublishSecretRef(ctx, secret.ToRef()); pubErr != nil {
				h.logger.Warn("failed to publish secret canonical record (legacy path)", zap.Error(pubErr))
			}
		}
	}
	return map[string]any{"secret": secret.ToRef(), "status": "created"}, nil
}

func (h *EncryptedRouteHandlers) UpdateSecret(ctx context.Context, request EncryptedRequest) (any, error) {
	if err := h.requireSecretDeps(); err != nil {
		return nil, err
	}
	var payload encryptedSecretPayload
	if err := decodeEncryptedPayload(request, &payload); err != nil {
		return nil, err
	}
	serviceID, err := parseEncryptedUUID(payload.ServiceID, "service ID")
	if err != nil {
		return nil, err
	}
	secretID, err := parseEncryptedUUID(payload.SecretID, "secret ID")
	if err != nil {
		return nil, err
	}
	if payload.Value == "" && payload.EncryptedValue == "" {
		return nil, fmt.Errorf("value is required (either value or encrypted_value)")
	}
	if err := h.authorizeServicePermission(ctx, request, serviceID, domain.PermWriteSecrets); err != nil {
		return nil, err
	}
	secret, err := h.secretForService(ctx, serviceID, secretID)
	if err != nil {
		return nil, err
	}
	method, err := parseSecretEncryptionMethod(payload.EncryptionMethod, secret.EncryptionMethod)
	if err != nil {
		return nil, err
	}
	var encrypted []byte
	if payload.EncryptedValue != "" {
		encrypted = []byte(payload.EncryptedValue)
	} else {
		encrypted, err = h.encryptor.Encrypt(payload.Value, method)
		if err != nil {
			return nil, fmt.Errorf("failed to encrypt secret")
		}
	}
	// Phase 3 N1 dual dispatch (§4.1): when the secret domain is enabled,
	// route through ProcessInProcess for shared idempotency with relay intents.
	if h.secretIntentEnabled() {
		content := BuildSecretIntentContent(serviceID, secretID, secret.Name, payload.Value, secret.EnvironmentID, method)
		if payload.EncryptedValue != "" {
			content["encrypted_value"] = payload.EncryptedValue
			delete(content, "value") // Don't pass plaintext when client pre-encrypted.
		}
		intent := &Intent{
			Domain:     "secret",
			Op:         "update",
			OrgID:      h.resolveSecretOrgID(ctx, serviceID),
			IntentID:   uuid.New().String(),
			Coordinate: secretID.String(),
			Content:    content,
			Actor:      normalizeEncryptedPubkey(request.Event.PubKey.Hex()),
		}
		if err := h.intentProcessor.ProcessInProcess(ctx, intent); err != nil {
			return nil, fmt.Errorf("failed to update secret: %w", err)
		}
	} else {
		secret.EncryptedValue = encrypted
		secret.EncryptionMethod = method
		secret.UpdatedAt = time.Now().UTC()
		if err := h.secrets.Update(ctx, secret); err != nil {
			return nil, fmt.Errorf("failed to update secret: %w", err)
		}
		// Legacy path: publish canonical record so relay state stays current.
		if h.secretPublisher != nil {
			if pubErr := h.secretPublisher.PublishSecretRef(ctx, secret.ToRef()); pubErr != nil {
				h.logger.Warn("failed to publish secret canonical record (legacy path)", zap.Error(pubErr))
			}
		}
	}
	if updated, _ := h.secrets.GetByID(ctx, secretID); updated != nil {
		secret = updated
	}
	return map[string]any{"secret": secret.ToRef(), "status": "updated"}, nil
}

func (h *EncryptedRouteHandlers) DeleteSecret(ctx context.Context, request EncryptedRequest) (any, error) {
	if err := h.requireSecretDeps(); err != nil {
		return nil, err
	}
	var payload encryptedSecretPayload
	if err := decodeEncryptedPayload(request, &payload); err != nil {
		return nil, err
	}
	serviceID, err := parseEncryptedUUID(payload.ServiceID, "service ID")
	if err != nil {
		return nil, err
	}
	secretID, err := parseEncryptedUUID(payload.SecretID, "secret ID")
	if err != nil {
		return nil, err
	}
	if err := h.authorizeServicePermission(ctx, request, serviceID, domain.PermWriteSecrets); err != nil {
		return nil, err
	}
	if _, err := h.secretForService(ctx, serviceID, secretID); err != nil {
		return nil, err
	}
	// Phase 3 N1 dual dispatch (§4.1): when the secret domain is enabled,
	// route through ProcessInProcess for shared idempotency with relay intents.
	if h.secretIntentEnabled() {
		intent := &Intent{
			Domain:     "secret",
			Op:         "delete",
			OrgID:      h.resolveSecretOrgID(ctx, serviceID),
			IntentID:   uuid.New().String(),
			Coordinate: secretID.String(),
			Content:    map[string]interface{}{"id": secretID.String()},
			Actor:      normalizeEncryptedPubkey(request.Event.PubKey.Hex()),
		}
		if err := h.intentProcessor.ProcessInProcess(ctx, intent); err != nil {
			return nil, fmt.Errorf("failed to delete secret: %w", err)
		}
	} else {
		if err := h.secrets.Delete(ctx, secretID); err != nil {
			return nil, fmt.Errorf("failed to delete secret")
		}
		// Legacy path: publish tombstone so relay state stays current.
		if h.secretPublisher != nil {
			if pubErr := h.secretPublisher.PublishSecretDeleted(ctx, secretID); pubErr != nil {
				h.logger.Warn("failed to publish secret tombstone (legacy path)", zap.Error(pubErr))
			}
		}
	}
	return map[string]string{"status": "deleted", "secret_id": secretID.String()}, nil
}

func (h *EncryptedRouteHandlers) RevealSecret(ctx context.Context, request EncryptedRequest) (any, error) {
	if err := h.requireSecretDeps(); err != nil {
		return nil, err
	}
	var payload encryptedSecretPayload
	if err := decodeEncryptedPayload(request, &payload); err != nil {
		return nil, err
	}
	serviceID, err := parseEncryptedUUID(payload.ServiceID, "service ID")
	if err != nil {
		return nil, err
	}
	secretID, err := parseEncryptedUUID(payload.SecretID, "secret ID")
	if err != nil {
		return nil, err
	}
	if err := h.authorizeServicePermission(ctx, request, serviceID, domain.PermReadSecrets); err != nil {
		return nil, err
	}
	secret, err := h.secretForService(ctx, serviceID, secretID)
	if err != nil {
		return nil, err
	}
	value, err := h.encryptor.Decrypt(secret.EncryptedValue, secret.EncryptionMethod)
	if err != nil {
		return nil, fmt.Errorf("failed to decrypt secret")
	}
	return map[string]any{"secret": secret.ToRef(), "value": value}, nil
}

func (h *EncryptedRouteHandlers) secretForService(ctx context.Context, serviceID, secretID uuid.UUID) (*domain.ServiceSecret, error) {
	secret, err := h.secrets.GetByID(ctx, secretID)
	if err != nil {
		return nil, fmt.Errorf("failed to look up secret")
	}
	if secret == nil {
		return nil, fmt.Errorf("secret not found")
	}
	if secret.ServiceID != serviceID {
		return nil, fmt.Errorf("secret does not belong to service")
	}
	return secret, nil
}

func (h *EncryptedRouteHandlers) authorizeServicePermission(ctx context.Context, request EncryptedRequest, serviceID uuid.UUID, permission domain.Permission) error {
	if h.services == nil || h.rbac == nil {
		return fmt.Errorf("encrypted route RBAC is not configured")
	}
	service, err := h.services.GetByID(ctx, serviceID)
	if err != nil {
		if err == repository.ErrNotFound {
			return fmt.Errorf("service not found")
		}
		return fmt.Errorf("failed to fetch service")
	}
	if service == nil {
		return fmt.Errorf("service not found")
	}
	if service.OrgID == uuid.Nil {
		return fmt.Errorf("service organization is not configured")
	}
	return h.rbac.CheckPermission(ctx, requestPrincipal(request), service.OrgID, permission)
}

func parseSecretEncryptionMethod(value string, fallback domain.EncryptionMethod) (domain.EncryptionMethod, error) {
	if strings.TrimSpace(value) == "" {
		return fallback, nil
	}
	method := domain.EncryptionMethod(strings.TrimSpace(value))
	switch method {
	case domain.EncryptionNIP44, domain.EncryptionAES256:
		return method, nil
	default:
		return "", fmt.Errorf("encryption_method must be 'nip44' or 'aes256gcm'")
	}
}

func (h *EncryptedRouteHandlers) GetRunLogs(ctx context.Context, request EncryptedRequest) (any, error) {
	if h.runs == nil || h.runLogs == nil {
		return nil, fmt.Errorf("encrypted deployment run log retrieval is not configured")
	}
	var payload struct {
		RunID  string `json:"run_id"`
		Tail   int    `json:"tail,omitempty"`
		Stream string `json:"stream,omitempty"`
	}
	if err := decodeEncryptedPayload(request, &payload); err != nil {
		return nil, err
	}
	runID, err := parseEncryptedUUID(payload.RunID, "run ID")
	if err != nil {
		return nil, err
	}
	run, err := h.runs.GetByID(ctx, runID)
	if err != nil {
		if err == repository.ErrNotFound {
			return nil, fmt.Errorf("deployment run not found")
		}
		return nil, fmt.Errorf("failed to fetch run")
	}
	if run == nil {
		return nil, fmt.Errorf("deployment run not found")
	}
	intent, err := h.authorizeRunPermission(ctx, request, run, domain.PermReadLogs)
	if err != nil {
		return nil, err
	}
	if !isTerminalEncryptedRunStatus(run.Status) {
		return nil, fmt.Errorf("run is still in progress; stored logs are available after completion")
	}
	logs, err := h.runLogs.FetchRunLogs(ctx, run)
	if err != nil {
		h.logger.Error("failed to fetch encrypted request run logs", zap.String("run_id", runID.String()), zap.Error(err))
		return nil, fmt.Errorf("failed to fetch logs")
	}
	if logs == nil {
		logs = &adapterruntime.RunLogs{RunID: runID}
	}
	if err := h.redactRunLogSecrets(ctx, intent, logs); err != nil {
		h.logger.Error("failed to redact encrypted request run logs", zap.String("run_id", runID.String()), zap.Error(err))
		return nil, fmt.Errorf("failed to safely prepare logs")
	}
	if payload.Tail > 0 {
		logs.Stdout = adapterruntime.TailLogs(logs.Stdout, payload.Tail)
		logs.Stderr = adapterruntime.TailLogs(logs.Stderr, payload.Tail)
	}
	stream := strings.TrimSpace(payload.Stream)
	if stream == "" {
		stream = "merged"
	}
	switch stream {
	case "stdout":
		logs.Stderr = ""
	case "stderr":
		logs.Stdout = ""
	case "merged":
		// keep both streams for tabbed UI callers
	default:
		return nil, fmt.Errorf("invalid stream parameter; use stdout, stderr, or merged")
	}
	return map[string]any{"logs": logs, "stream": stream}, nil
}

func (h *EncryptedRouteHandlers) authorizeRunPermission(ctx context.Context, request EncryptedRequest, run *domain.DeploymentRun, permission domain.Permission) (*domain.DeploymentIntent, error) {
	if h.intents == nil {
		return nil, fmt.Errorf("deployment intent lookup is not configured")
	}
	intent, err := h.intents.GetByID(ctx, run.DeploymentIntentID)
	if err != nil {
		if err == repository.ErrNotFound {
			return nil, fmt.Errorf("deployment intent not found")
		}
		return nil, fmt.Errorf("failed to fetch deployment intent")
	}
	if intent == nil {
		return nil, fmt.Errorf("deployment intent not found")
	}
	if err := h.authorizeServicePermission(ctx, request, intent.ServiceID, permission); err != nil {
		return nil, err
	}
	return intent, nil
}

func (h *EncryptedRouteHandlers) redactRunLogSecrets(ctx context.Context, intent *domain.DeploymentIntent, logs *adapterruntime.RunLogs) error {
	if intent == nil || intent.DesiredState == nil || len(intent.DesiredState.SecretRefs) == 0 {
		return nil
	}
	if h.secrets == nil || h.encryptor == nil {
		return fmt.Errorf("secret redaction dependencies are not configured")
	}
	values := make([]string, 0, len(intent.DesiredState.SecretRefs))
	seen := make(map[uuid.UUID]struct{}, len(intent.DesiredState.SecretRefs))
	for _, ref := range intent.DesiredState.SecretRefs {
		if ref.SecretID == uuid.Nil {
			return fmt.Errorf("desired secret reference is incomplete")
		}
		if _, ok := seen[ref.SecretID]; ok {
			continue
		}
		seen[ref.SecretID] = struct{}{}
		history, ok := h.secrets.(secretVersionHistoryLister)
		if !ok {
			return fmt.Errorf("referenced secret version history is unavailable")
		}
		versions, err := history.ListVersions(ctx, ref.SecretID)
		if err != nil {
			return fmt.Errorf("load referenced secret history")
		}
		if len(versions) == 0 {
			return fmt.Errorf("referenced secret has no retained versions")
		}
		for i := range versions {
			value, err := h.encryptor.Decrypt(versions[i].EncryptedValue, versions[i].EncryptionMethod)
			if err != nil {
				return fmt.Errorf("decrypt referenced secret")
			}
			if value != "" {
				values = append(values, value)
			}
		}
	}
	// Longest first prevents a short secret that is a substring of another from
	// leaving a partially-redacted value behind.
	sort.Slice(values, func(i, j int) bool { return len(values[i]) > len(values[j]) })
	redact := func(input string) string {
		for _, value := range values {
			input = strings.ReplaceAll(input, value, "[REDACTED]")
			if encoded, err := json.Marshal(value); err == nil && len(encoded) >= 2 {
				input = strings.ReplaceAll(input, string(encoded[1:len(encoded)-1]), "[REDACTED]")
			}
		}
		return input
	}
	logs.Stdout = redact(logs.Stdout)
	logs.Stderr = redact(logs.Stderr)
	return nil
}

func isTerminalEncryptedRunStatus(status domain.DeploymentRunStatus) bool {
	switch status {
	case domain.RunStatusSucceeded, domain.RunStatusFailed, domain.RunStatusCancelled, domain.RunStatusTimeout:
		return true
	default:
		return false
	}
}

func (h *EncryptedRouteHandlers) VerifyArtifactSignatures(ctx context.Context, request EncryptedRequest) (any, error) {
	if h.signatures == nil || h.artifacts == nil || h.signVerifier == nil {
		return nil, fmt.Errorf("encrypted artifact signature request handling is not configured")
	}
	var payload struct {
		ArtifactID string `json:"artifact_id"`
	}
	if err := decodeEncryptedPayload(request, &payload); err != nil {
		return nil, err
	}
	artifactID, err := parseEncryptedUUID(payload.ArtifactID, "artifact ID")
	if err != nil {
		return nil, err
	}
	artifact, err := h.artifacts.GetByID(ctx, artifactID)
	if err != nil {
		if err == repository.ErrNotFound {
			return nil, fmt.Errorf("artifact not found")
		}
		return nil, fmt.Errorf("failed to fetch artifact")
	}
	if artifact == nil {
		return nil, fmt.Errorf("artifact not found")
	}
	if err := h.authorizeServicePermission(ctx, request, artifact.ServiceID, domain.PermWriteServices); err != nil {
		return nil, err
	}
	sigs, err := h.signVerifier.VerifySignatures(ctx, artifact)
	if err != nil {
		return nil, fmt.Errorf("verifying signatures: %w", err)
	}
	var stored int
	counts := map[domain.SignatureVerificationStatus]int{
		domain.SignatureStatusVerified:   0,
		domain.SignatureStatusDiscovered: 0,
		domain.SignatureStatusRejected:   0,
		domain.SignatureStatusError:      0,
	}
	for i := range sigs {
		sig := &sigs[i]
		if sig.ID == uuid.Nil {
			sig.ID = uuid.New()
		}
		if sig.ArtifactID == uuid.Nil {
			sig.ArtifactID = artifactID
		}
		sig.NormalizeVerificationStatus()
		counts[sig.VerificationStatus]++
		if err := h.signatures.Create(ctx, sig); err != nil {
			h.logger.Warn("failed to store signature record", zap.String("artifact_id", artifactID.String()), zap.String("signature_id", sig.ID.String()), zap.Error(err))
			continue
		}
		stored++
	}
	return map[string]any{
		"artifact_id": artifactID.String(),
		"found":       len(sigs),
		"stored":      stored,
		"verified":    counts[domain.SignatureStatusVerified],
		"discovered":  counts[domain.SignatureStatusDiscovered],
		"rejected":    counts[domain.SignatureStatusRejected],
		"errors":      counts[domain.SignatureStatusError],
		"signatures":  sigs,
	}, nil
}

// --- Phase 3 N1 notification channel dual-dispatch handlers ---
//
// These ContextVM handlers translate web-originated notification channel
// mutations into in-process intents and delegate to ProcessInProcess.
// The old B-27 handlers in notification_encrypted_handlers.go are deleted;
// these are the sole remaining path for web-originated channel mutations
// until O1 gift-wrap ingress is live.

// CreateNotificationChannel handles notification/create ContextVM requests.
// When the notification domain is enabled, it dual-dispatches through the
// intent processor. Otherwise it falls back to the legacy path: tenant RBAC,
// repo write, canonical publish, dispatcher notify.
func (h *EncryptedRouteHandlers) CreateNotificationChannel(ctx context.Context, request ContextVMRequest) (any, error) {
	var payload notificationChannelPayload
	if err := json.Unmarshal(request.RPC.Params, &payload); err != nil {
		return nil, fmt.Errorf("invalid notification channel payload: %w", err)
	}
	if strings.TrimSpace(payload.Name) == "" {
		return nil, fmt.Errorf("channel name is required")
	}
	if strings.TrimSpace(payload.ChannelType) == "" {
		return nil, fmt.Errorf("channel_type is required")
	}

	ch := buildNotificationChannelFromPayload(payload)
	if ch.ID == uuid.Nil {
		ch.ID = domain.NewEntityID()
	}

	if h.notificationIntentEnabled() {
		content := BuildNotificationIntentContent(ch)
		intent := &Intent{
			Domain:     "notification",
			Op:         "create",
			OrgID:      ch.OrgID,
			IntentID:   uuid.New().String(),
			Coordinate: ch.ID.String(),
			Content:    content,
			Actor:      normalizeEncryptedPubkey(request.Event.PubKey.Hex()),
		}
		if err := h.intentProcessor.ProcessInProcess(ctx, intent); err != nil {
			return nil, fmt.Errorf("failed to create notification channel: %w", err)
		}
		return map[string]any{"channel": content, "status": "created"}, nil
	}

	// Legacy path: authorise with tenant RBAC, write via repo, publish, notify.
	if err := h.authorizeNotificationOrg(ctx, request, ch.OrgID, domain.PermManageSettings); err != nil {
		return nil, err
	}
	now := time.Now().UTC()
	ch.CreatedAt = now
	ch.UpdatedAt = now
	if err := h.notifRepo.CreateChannel(ctx, ch); err != nil {
		return nil, fmt.Errorf("failed to create notification channel: %w", err)
	}
	if h.notifPublisher != nil {
		if pubErr := h.notifPublisher.PublishChannel(ctx, ch); pubErr != nil {
			h.logger.Warn("failed to publish notification channel (legacy path)", zap.Error(pubErr))
		}
	}
	if h.notifNotifier != nil {
		h.notifNotifier.OnChannelChanged(ch, false)
	}
	return map[string]any{"channel": BuildNotificationIntentContent(ch), "status": "created"}, nil
}

// UpdateNotificationChannel handles notification/update ContextVM requests.
// When the notification domain is enabled, it dual-dispatches through the
// intent processor. Otherwise it falls back to the legacy path.
func (h *EncryptedRouteHandlers) UpdateNotificationChannel(ctx context.Context, request ContextVMRequest) (any, error) {
	var payload notificationChannelPayload
	if err := json.Unmarshal(request.RPC.Params, &payload); err != nil {
		return nil, fmt.Errorf("invalid notification channel payload: %w", err)
	}
	channelID, err := uuid.Parse(strings.TrimSpace(payload.ID))
	if err != nil || channelID == uuid.Nil {
		return nil, fmt.Errorf("channel id is required for update")
	}

	ch := buildNotificationChannelFromPayload(payload)
	ch.ID = channelID

	if h.notificationIntentEnabled() {
		content := BuildNotificationIntentContent(ch)
		intent := &Intent{
			Domain:     "notification",
			Op:         "update",
			OrgID:      ch.OrgID,
			IntentID:   uuid.New().String(),
			Coordinate: channelID.String(),
			Content:    content,
			Actor:      normalizeEncryptedPubkey(request.Event.PubKey.Hex()),
		}
		if err := h.intentProcessor.ProcessInProcess(ctx, intent); err != nil {
			return nil, fmt.Errorf("failed to update notification channel: %w", err)
		}
		return map[string]any{"channel": content, "status": "updated"}, nil
	}

	// Legacy path: load existing for org-scoped RBAC, merge, write, publish, notify.
	existing, loadErr := h.notifRepo.GetChannelByID(ctx, channelID)
	if loadErr != nil || existing == nil {
		return nil, fmt.Errorf("notification channel not found")
	}
	if err := h.authorizeNotificationOrg(ctx, request, existing.OrgID, domain.PermManageSettings); err != nil {
		return nil, err
	}
	mergeNotificationChannelOntoExisting(existing, ch)
	existing.UpdatedAt = time.Now().UTC()
	if err := h.notifRepo.UpdateChannel(ctx, existing); err != nil {
		return nil, fmt.Errorf("failed to update notification channel: %w", err)
	}
	if h.notifPublisher != nil {
		if pubErr := h.notifPublisher.PublishChannel(ctx, existing); pubErr != nil {
			h.logger.Warn("failed to publish notification channel (legacy path)", zap.Error(pubErr))
		}
	}
	if h.notifNotifier != nil {
		h.notifNotifier.OnChannelChanged(existing, false)
	}
	return map[string]any{"channel": BuildNotificationIntentContent(existing), "status": "updated"}, nil
}

// DeleteNotificationChannel handles notification/delete ContextVM requests.
// When the notification domain is enabled, it dual-dispatches through the
// intent processor. Otherwise it falls back to the legacy path.
func (h *EncryptedRouteHandlers) DeleteNotificationChannel(ctx context.Context, request ContextVMRequest) (any, error) {
	var payload notificationChannelPayload
	if err := json.Unmarshal(request.RPC.Params, &payload); err != nil {
		return nil, fmt.Errorf("invalid notification channel payload: %w", err)
	}
	channelID, err := uuid.Parse(strings.TrimSpace(payload.ID))
	if err != nil || channelID == uuid.Nil {
		return nil, fmt.Errorf("channel id is required for delete")
	}

	if h.notificationIntentEnabled() {
		content := map[string]interface{}{"id": channelID.String()}
		intent := &Intent{
			Domain:     "notification",
			Op:         "delete",
			OrgID:      uuid.Nil, // resolved from channel by handler
			IntentID:   uuid.New().String(),
			Coordinate: channelID.String(),
			Content:    content,
			Actor:      normalizeEncryptedPubkey(request.Event.PubKey.Hex()),
		}
		if err := h.intentProcessor.ProcessInProcess(ctx, intent); err != nil {
			return nil, fmt.Errorf("failed to delete notification channel: %w", err)
		}
		return map[string]any{"status": "deleted", "channel_id": channelID.String()}, nil
	}

	// Legacy path: load for RBAC + notifier, delete, publish tombstone, notify.
	existing, loadErr := h.notifRepo.GetChannelByID(ctx, channelID)
	if loadErr != nil || existing == nil {
		return nil, fmt.Errorf("notification channel not found")
	}
	if err := h.authorizeNotificationOrg(ctx, request, existing.OrgID, domain.PermManageSettings); err != nil {
		return nil, err
	}
	if err := h.notifRepo.DeleteChannel(ctx, channelID); err != nil {
		return nil, fmt.Errorf("failed to delete notification channel: %w", err)
	}
	if h.notifPublisher != nil {
		if pubErr := h.notifPublisher.PublishChannelDeleted(ctx, channelID); pubErr != nil {
			h.logger.Warn("failed to publish notification channel tombstone (legacy path)", zap.Error(pubErr))
		}
	}
	if h.notifNotifier != nil {
		h.notifNotifier.OnChannelChanged(existing, true)
	}
	return map[string]any{"status": "deleted", "channel_id": channelID.String()}, nil
}

// authorizeNotificationOrg checks ContextVM tenant RBAC for a notification
// channel mutation against the given org. Used by the legacy (non-intent) path.
func (h *EncryptedRouteHandlers) authorizeNotificationOrg(ctx context.Context, request ContextVMRequest, orgID uuid.UUID, permission domain.Permission) error {
	if orgID == uuid.Nil {
		return fmt.Errorf("notification channel organization is required")
	}
	if h.rbac == nil {
		return fmt.Errorf("notification RBAC is not configured")
	}
	if request.Event == nil {
		return fmt.Errorf("signed ContextVM request event is required")
	}
	return h.rbac.CheckPermission(ctx, requestPrincipal(EncryptedRequest{Event: request.Event}), orgID, permission)
}

// buildNotificationChannelFromPayload converts a ContextVM payload into a
// domain.NotificationChannel for intent content building.
func buildNotificationChannelFromPayload(payload notificationChannelPayload) *domain.NotificationChannel {
	ch := &domain.NotificationChannel{
		Name:        strings.TrimSpace(payload.Name),
		ChannelType: domain.ChannelType(strings.TrimSpace(payload.ChannelType)),
		Config:      payload.Config,
		EventFilter: payload.EventFilter,
		Enabled:     true,
	}
	if payload.Enabled != nil {
		ch.Enabled = *payload.Enabled
	}
	if id, err := uuid.Parse(strings.TrimSpace(payload.ID)); err == nil {
		ch.ID = id
	}
	if orgID, err := uuid.Parse(strings.TrimSpace(payload.OrgID)); err == nil {
		ch.OrgID = orgID
	}
	return ch
}
