package controlplane

import (
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"testing"

	"golang.org/x/crypto/chacha20poly1305"
)

// TestPaymentSecurityCrossLanguageFixture asserts the committed fleet-OCK
// payment/finding vectors match the daemon's AEAD and AD serialization.
func TestPaymentSecurityCrossLanguageFixture(t *testing.T) {
	var keyBytes [32]byte
	for i := range keyBytes {
		keyBytes[i] = 0xbb
	}
	key := OrgContentKey{OrgID: "fleet", Version: 3, Key: keyBytes}
	type record struct {
		Name       string         `json:"name"`
		LegacyKind int            `json:"legacy_kind"`
		DTag       string         `json:"d_tag"`
		Topic      string         `json:"topic"`
		Payload    map[string]any `json:"payload"`
		Encrypted  string         `json:"encrypted_content"`
	}
	records := []record{
		{Name: "payment", LegacyKind: 32011, DTag: "payment:11111111-1111-7111-8111-111111111111", Topic: "payment-record", Payload: map[string]any{"id": "11111111-1111-7111-8111-111111111111", "worker_pubkey": "worker-a", "amount_sats": 42, "status": "sent", "direction": "payment"}},
		{Name: "finding", LegacyKind: 32012, DTag: "security:finding:hash-a", Topic: "security-finding", Payload: map[string]any{"id": "finding-a", "finding_key_hash": "hash-a", "run_id": "run-a", "target_key_hash": "target-a", "severity": "high", "summary": "Go fixture finding"}},
		{Name: "schedule", LegacyKind: 32013, DTag: "security:schedule:22222222-2222-7222-8222-222222222222", Topic: "security-schedule", Payload: map[string]any{"id": "22222222-2222-7222-8222-222222222222", "target_key_hash": "target-a", "enabled": true, "interval_seconds": 86400}},
		{Name: "detail-part-0", LegacyKind: 32014, DTag: "security:finding-detail:hash-a:part:0", Topic: "security-finding-detail", Payload: map[string]any{"finding_key_hash": "hash-a", "part_index": 0, "total_parts": 2, "details": "first "}},
		{Name: "detail-part-1", LegacyKind: 32014, DTag: "security:finding-detail:hash-a:part:1", Topic: "security-finding-detail", Payload: map[string]any{"finding_key_hash": "hash-a", "part_index": 1, "total_parts": 2, "details": "second"}},
	}
	for i := range records {
		plaintext, err := json.Marshal(records[i].Payload)
		if err != nil {
			t.Fatal(err)
		}
		ctx := ConfidentialRecordContext{LegacyKind: records[i].LegacyKind, DTag: records[i].DTag, Topic: records[i].Topic}
		adBytes, err := json.Marshal(confidentialAssociatedData(key, ctx))
		if err != nil {
			t.Fatal(err)
		}
		aead, err := chacha20poly1305.NewX(key.Key[:])
		if err != nil {
			t.Fatal(err)
		}
		nonce := make([]byte, chacha20poly1305.NonceSizeX)
		for j := range nonce {
			nonce[j] = byte(i*24 + j + 1)
		}
		ciphertext := aead.Seal(nil, nonce, plaintext, adBytes)
		envelope := ConfidentialEnvelope{
			Schema: ConfidentialSchema, Algorithm: ConfidentialAlgorithm,
			KeyOrg: key.OrgID, KeyRef: key.KeyRef(), KeyVersion: key.KeyVersion(),
			Nonce:          base64.RawStdEncoding.EncodeToString(nonce),
			Ciphertext:     base64.RawStdEncoding.EncodeToString(ciphertext),
			AssociatedData: confidentialAssociatedData(key, ctx),
		}
		encoded, err := json.Marshal(envelope)
		if err != nil {
			t.Fatal(err)
		}
		records[i].Encrypted = string(encoded)
		roundTrip, err := DecryptConfidentialContent(key, records[i].Encrypted, ctx)
		if err != nil || string(roundTrip) != string(plaintext) {
			t.Fatalf("Go decrypt %s: %v", records[i].Name, err)
		}
	}
	fixture := map[string]any{
		"_comment": "Generated by TestPaymentSecurityCrossLanguageFixture; regenerate with BAHIA_REGEN_FIXTURE=1 go test ./internal/controlplane/",
		"ock":      map[string]any{"org_id": key.OrgID, "version": key.Version, "key_b64": base64.RawStdEncoding.EncodeToString(key.Key[:])},
		"records":  records,
	}
	serialized, err := json.MarshalIndent(fixture, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	serialized = append(serialized, '\n')
	_, thisFile, _, _ := runtime.Caller(0)
	path := filepath.Join(filepath.Dir(thisFile), "..", "..", "web", "tests", "fixtures", "paysec-confidential.json")
	if os.Getenv("BAHIA_REGEN_FIXTURE") == "1" {
		if err := os.WriteFile(path, serialized, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	committed, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(committed) != string(serialized) {
		t.Fatal("committed payment/security fixture differs from Go output")
	}
}
