FROM alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

RUN apk add --no-cache ca-certificates tzdata docker-cli docker-cli-compose wget

COPY .recovery-bin/bahia-server /usr/local/bin/bahia-server
COPY .recovery-bin/bahia-relay /usr/local/bin/bahia-relay

EXPOSE 8080 3334

ENTRYPOINT ["bahia-server"]
