FROM alpine:3.21

RUN apk add --no-cache ca-certificates tzdata docker-cli docker-cli-compose wget

COPY .recovery-bin/bahia-server /usr/local/bin/bahia-server
COPY .recovery-bin/bahia-relay /usr/local/bin/bahia-relay

EXPOSE 8080 3334

ENTRYPOINT ["bahia-server"]
