-- 000061_route_canary_health_path_classification: admit the
-- health_path_not_discriminating classification.
--
-- 000060 pinned the classification set in CHECK constraints. A later change
-- added health_path_not_discriminating to the domain without widening those
-- constraints, so the route canary supervisor failed every upsert with
-- SQLSTATE 23514 on a live candidate. 000060 is already applied in production
-- and is therefore immutable; the set is widened here instead.
--
-- The constraints are given explicit names so a future classification can be
-- admitted by name rather than by rediscovering a generated identifier.

DO $$
DECLARE
  constraint_row record;
BEGIN
  -- 000060 declared these inline, so their names were generated by PostgreSQL.
  -- Locate them by definition rather than assuming a naming convention.
  FOR constraint_row IN
    SELECT conrelid::regclass::text AS table_name, conname
    FROM pg_constraint
    WHERE contype = 'c'
      AND conrelid IN ('route_canary_state'::regclass, 'route_canary_events'::regclass)
      AND pg_get_constraintdef(oid) LIKE '%body_mismatch%'
  LOOP
    EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I',
                   constraint_row.table_name, constraint_row.conname);
  END LOOP;
END $$;

ALTER TABLE route_canary_state
  ADD CONSTRAINT route_canary_state_classification_check
  CHECK (classification IN (
    'route_ok', 'dns_unresolved', 'connect_failed', 'tls_invalid',
    'tls_expiring', 'upstream_error', 'status_mismatch', 'body_mismatch',
    'health_path_not_discriminating'
  ));

ALTER TABLE route_canary_events
  ADD CONSTRAINT route_canary_events_classification_check
  CHECK (classification IN (
    'route_ok', 'dns_unresolved', 'connect_failed', 'tls_invalid',
    'tls_expiring', 'upstream_error', 'status_mismatch', 'body_mismatch',
    'health_path_not_discriminating'
  ));
