/**
 * Cross-language test vector for the confidential cp-state crypto.
 *
 * The primary cross-language test reads a fixture generated by Go
 * (internal/controlplane/cross_language_fixture_test.go) and decrypts
 * it with the JS implementation. If either side drifts, one test fails:
 * - Go test: asserts the committed fixture matches its generated output
 * - JS test: asserts the fixture decrypts to the expected plaintext
 *
 * Self-tests also exercise the JS implementation in isolation.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, it, expect } from 'vitest';
import { xchacha20poly1305 } from '@noble/ciphers/chacha.js';
import {
  decryptConfidentialContent,
  parseConfidentialEnvelope,
  versionFromEnvelope,
  unmarshalOCKWrap,
  parseKeyEnvelopeDTag,
  isConfidentialEnvelope,
  base64Encode,
  base64Decode,
  CONFIDENTIAL_SCHEMA,
  CONFIDENTIAL_ALGORITHM,
  OCK_WRAP_SCHEMA,
  KEY_ENVELOPE_TOPIC
} from '../../src/lib/nostr/confidential.js';

// ---------------------------------------------------------------------------
// Load Go-generated fixture
// ---------------------------------------------------------------------------

const fixturePath = join(process.cwd(), 'tests', 'fixtures', 'cross-language-crypto.json');
let goFixture;
try {
  // Try from web/ cwd first, then from parent
  goFixture = JSON.parse(readFileSync(fixturePath, 'utf-8'));
} catch {
  goFixture = JSON.parse(readFileSync(join(process.cwd(), '..', 'web', 'tests', 'fixtures', 'cross-language-crypto.json'), 'utf-8'));
}

// ---------------------------------------------------------------------------
// Deterministic test key material for JS self-tests
// ---------------------------------------------------------------------------

const TEST_OCK_BYTES = new Uint8Array(32);
TEST_OCK_BYTES[0] = 0xAA;
TEST_OCK_BYTES[1] = 0xBB;
TEST_OCK_BYTES[31] = 0xFF;

const TEST_ORG_ID = 'test-org-123';
const TEST_VERSION = 1;
const TEST_LEGACY_KIND = 32006;
const TEST_D_TAG = 'org:member:test-org-123:abc123pubkey';
const TEST_TOPIC = 'org-member';

const TEST_PLAINTEXT = '{"org_id":"test-org-123","pubkey":"abc123pubkey","role":"admin","deleted":false}';

function buildTestEnvelope() {
  const ad = {
    schema: CONFIDENTIAL_SCHEMA,
    key_org: TEST_ORG_ID,
    key_ref: 'ock:' + TEST_ORG_ID,
    key_version: 'v' + TEST_VERSION,
    legacy_kind: String(TEST_LEGACY_KIND),
    d: TEST_D_TAG,
    t: TEST_TOPIC
  };

  const sortedKeys = Object.keys(ad).sort();
  const sortedAD = {};
  for (const k of sortedKeys) {
    sortedAD[k] = ad[k];
  }
  const adBytes = new TextEncoder().encode(JSON.stringify(sortedAD));

  const nonce = new Uint8Array(24);
  nonce[0] = 0x01;
  nonce[23] = 0x42;

  const plaintextBytes = new TextEncoder().encode(TEST_PLAINTEXT);
  const cipher = xchacha20poly1305(TEST_OCK_BYTES, nonce, adBytes);
  const ciphertext = cipher.encrypt(plaintextBytes);

  return JSON.stringify({
    schema: CONFIDENTIAL_SCHEMA,
    algorithm: CONFIDENTIAL_ALGORITHM,
    key_org: TEST_ORG_ID,
    key_ref: 'ock:' + TEST_ORG_ID,
    key_version: 'v' + TEST_VERSION,
    nonce: base64Encode(nonce),
    ciphertext: base64Encode(ciphertext),
    associated_data: ad,
    service_inner: ''
  });
}

// ---------------------------------------------------------------------------
// Cross-language tests (Go-generated fixture → JS decrypt)
// ---------------------------------------------------------------------------

describe('cross-language crypto fixture (Go → JS)', () => {
  it('decrypts Go-encrypted member record with OCK from fixture', () => {
    const ockKeyBytes = base64Decode(goFixture.ock.key_b64);
    const ock = {
      orgID: goFixture.ock.org_id,
      version: goFixture.ock.version,
      key: ockKeyBytes
    };
    const recordCtx = {
      legacyKind: goFixture.member_record.legacy_kind,
      dTag: goFixture.member_record.d_tag,
      topic: goFixture.member_record.topic
    };

    const result = decryptConfidentialContent(ock, goFixture.member_record.encrypted_content, recordCtx);
    expect(result).toBe(goFixture.member_record.plaintext);

    // Parse the plaintext and verify the role
    const member = JSON.parse(result);
    expect(member.role).toBe('admin');
    expect(member.org_id).toBe('org-fixture');
  });

  it('associated data bytes match Go encoding/json output', () => {
    const ockKeyBytes = base64Decode(goFixture.ock.key_b64);
    const ock = {
      orgID: goFixture.ock.org_id,
      version: goFixture.ock.version,
      key: ockKeyBytes
    };
    const recordCtx = {
      legacyKind: goFixture.member_record.legacy_kind,
      dTag: goFixture.member_record.d_tag,
      topic: goFixture.member_record.topic
    };

    // Build AD the same way the decrypt path does
    const ad = {
      d: recordCtx.dTag,
      key_org: ock.orgID,
      key_ref: 'ock:' + ock.orgID,
      key_version: 'v' + ock.version,
      legacy_kind: String(recordCtx.legacyKind),
      schema: CONFIDENTIAL_SCHEMA,
      t: recordCtx.topic
    };
    const jsADJSON = JSON.stringify(ad);
    expect(jsADJSON).toBe(goFixture.associated_data_json);
  });

  it('parses OCK wrap payload from Go fixture', () => {
    const { key, recipientPubkey } = unmarshalOCKWrap(goFixture.key_envelope.ock_wrap_json);
    expect(key.orgID).toBe(goFixture.ock.org_id);
    expect(key.version).toBe(goFixture.ock.version);
    expect(recipientPubkey).toBe(goFixture.member_pubkey);

    // The key bytes must match
    const expectedKeyBytes = base64Decode(goFixture.ock.key_b64);
    expect(key.key).toEqual(expectedKeyBytes);
  });

  it('parses key envelope d-tag from Go fixture', () => {
    const result = parseKeyEnvelopeDTag(goFixture.key_envelope.d_tag);
    expect(result).toEqual({
      orgID: goFixture.ock.org_id,
      version: goFixture.ock.version,
      handle: 'fixture-handle'
    });
  });

  it('version extraction matches Go fixture', () => {
    const { orgID, version } = versionFromEnvelope(goFixture.member_record.encrypted_content);
    expect(orgID).toBe(goFixture.ock.org_id);
    expect(version).toBe(goFixture.ock.version);
  });
});

// ---------------------------------------------------------------------------
// JS self-tests
// ---------------------------------------------------------------------------

describe('confidential crypto', () => {
  describe('decryptConfidentialContent', () => {
    it('decrypts an AEAD envelope with correct OCK and record context', () => {
      const envelope = buildTestEnvelope();
      const ock = { orgID: TEST_ORG_ID, version: TEST_VERSION, key: TEST_OCK_BYTES };
      const recordCtx = {
        legacyKind: TEST_LEGACY_KIND,
        dTag: TEST_D_TAG,
        topic: TEST_TOPIC
      };

      const result = decryptConfidentialContent(ock, envelope, recordCtx);
      expect(result).toBe(TEST_PLAINTEXT);
    });

    it('rejects wrong key version', () => {
      const envelope = buildTestEnvelope();
      const wrongOck = { orgID: TEST_ORG_ID, version: 2, key: TEST_OCK_BYTES };
      const recordCtx = {
        legacyKind: TEST_LEGACY_KIND,
        dTag: TEST_D_TAG,
        topic: TEST_TOPIC
      };

      expect(() => decryptConfidentialContent(wrongOck, envelope, recordCtx)).toThrow('AD mismatch');
    });

    it('rejects wrong d-tag (AD binding prevents ciphertext replay)', () => {
      const envelope = buildTestEnvelope();
      const ock = { orgID: TEST_ORG_ID, version: TEST_VERSION, key: TEST_OCK_BYTES };
      const wrongCtx = {
        legacyKind: TEST_LEGACY_KIND,
        dTag: 'org:member:other-org:xyz',
        topic: TEST_TOPIC
      };

      expect(() => decryptConfidentialContent(ock, envelope, wrongCtx)).toThrow('AD mismatch');
    });

    it('rejects wrong key bytes (AEAD auth failure)', () => {
      const envelope = buildTestEnvelope();
      const wrongKey = new Uint8Array(32);
      wrongKey[0] = 0xFF;
      const ock = { orgID: TEST_ORG_ID, version: TEST_VERSION, key: wrongKey };
      const recordCtx = {
        legacyKind: TEST_LEGACY_KIND,
        dTag: TEST_D_TAG,
        topic: TEST_TOPIC
      };

      expect(() => decryptConfidentialContent(ock, envelope, recordCtx)).toThrow();
    });
  });

  describe('parseConfidentialEnvelope', () => {
    it('parses a valid envelope', () => {
      const envelope = buildTestEnvelope();
      const parsed = parseConfidentialEnvelope(envelope);
      expect(parsed.schema).toBe(CONFIDENTIAL_SCHEMA);
      expect(parsed.algorithm).toBe(CONFIDENTIAL_ALGORITHM);
      expect(parsed.key_org).toBe(TEST_ORG_ID);
    });

    it('rejects unknown schema', () => {
      const bad = JSON.stringify({ schema: 'unknown' });
      expect(() => parseConfidentialEnvelope(bad)).toThrow('unknown confidential schema');
    });
  });

  describe('versionFromEnvelope', () => {
    it('extracts org ID and version', () => {
      const envelope = buildTestEnvelope();
      const { orgID, version } = versionFromEnvelope(envelope);
      expect(orgID).toBe(TEST_ORG_ID);
      expect(version).toBe(1);
    });
  });

  describe('unmarshalOCKWrap', () => {
    it('deserializes a valid OCK wrap payload', () => {
      const payload = JSON.stringify({
        schema: OCK_WRAP_SCHEMA,
        org_id: TEST_ORG_ID,
        key_ref: 'ock:' + TEST_ORG_ID,
        version: 1,
        key: base64Encode(TEST_OCK_BYTES),
        recipient_pubkey: 'abc123def456'
      });

      const { key, recipientPubkey } = unmarshalOCKWrap(payload);
      expect(key.orgID).toBe(TEST_ORG_ID);
      expect(key.version).toBe(1);
      expect(key.key).toEqual(TEST_OCK_BYTES);
      expect(recipientPubkey).toBe('abc123def456');
    });

    it('rejects unknown schema', () => {
      const bad = JSON.stringify({ schema: 'wrong', org_id: 'x', key: base64Encode(TEST_OCK_BYTES) });
      expect(() => unmarshalOCKWrap(bad)).toThrow('unknown OCK wrap schema');
    });

    it('rejects wrong key length', () => {
      const bad = JSON.stringify({
        schema: OCK_WRAP_SCHEMA,
        org_id: 'x',
        key: base64Encode(new Uint8Array(16)),
        version: 1
      });
      expect(() => unmarshalOCKWrap(bad)).toThrow('32 bytes');
    });
  });

  describe('parseKeyEnvelopeDTag', () => {
    it('parses org-key:<orgID>:v<N>:<handle>', () => {
      const result = parseKeyEnvelopeDTag('org-key:my-org:v3:abcdef0123456789');
      expect(result).toEqual({
        orgID: 'my-org',
        version: 3,
        handle: 'abcdef0123456789'
      });
    });

    it('returns null for non-matching d-tags', () => {
      expect(parseKeyEnvelopeDTag('org:member:xyz')).toBeNull();
      expect(parseKeyEnvelopeDTag('')).toBeNull();
      expect(parseKeyEnvelopeDTag(null)).toBeNull();
    });
  });

  describe('isConfidentialEnvelope', () => {
    it('returns true for valid envelopes', () => {
      expect(isConfidentialEnvelope(buildTestEnvelope())).toBe(true);
    });

    it('returns false for non-envelope content', () => {
      expect(isConfidentialEnvelope('{"name":"test"}')).toBe(false);
      expect(isConfidentialEnvelope(null)).toBe(false);
      expect(isConfidentialEnvelope('')).toBe(false);
      expect(isConfidentialEnvelope('not json')).toBe(false);
    });
  });

  describe('base64 round-trip', () => {
    it('encodes and decodes correctly (raw standard, no padding)', () => {
      const original = new Uint8Array([0, 1, 2, 255, 128, 64, 32]);
      const encoded = base64Encode(original);
      expect(encoded).not.toContain('=');
      const decoded = base64Decode(encoded);
      expect(decoded).toEqual(original);
    });
  });
});

describe('OCK never persisted to storage', () => {
  it('OCK is never written to localStorage', () => {
    const allKeys = Object.keys(localStorage);
    const ockKeys = allKeys.filter(k =>
      k.includes('ock') || k.includes('content_key') || k.includes('org_key')
    );
    expect(ockKeys).toEqual([]);
  });
});
