/**
 * Deprecated facade retained for import compatibility.
 *
 * Production Bahia web code must use canonical kind constants plus semantic
 * domain/schema tags from ./kinds.gen.js. Old Bahia request/status/result/read-
 * model kind aliases are intentionally not re-exported here.
 */
import * as gen from './kinds.gen.js';

export * from './kinds.gen.js';

export const BAHIA_KINDS = {
  CONTEXTVM_MESSAGE: gen.CONTEXTVM_MESSAGE,
  CONTEXTVM_GIFT_WRAP: gen.CONTEXTVM_GIFT_WRAP,
  CONTEXTVM_EPHEMERAL_GIFT_WRAP: gen.CONTEXTVM_EPHEMERAL_GIFT_WRAP,
  CASCADIA_CONTROLPLANE_STATE: gen.CASCADIA_CONTROLPLANE_STATE,
  CASCADIA_AUDIT: gen.CASCADIA_AUDIT,
  NIP38_STATUS: gen.NIP38_STATUS,
  NIP51_RELAY_SET: gen.NIP51_RELAY_SET,
  NIP51_DM_RELAY_LIST: gen.NIP51_DM_RELAY_LIST,
  NIP78_APP_DATA: gen.NIP78_APP_DATA,
  CONTEXTVM_SERVER_ANNOUNCEMENT: gen.CONTEXTVM_SERVER_ANNOUNCEMENT,
  CONTEXTVM_TOOLS_ANNOUNCEMENT: gen.CONTEXTVM_TOOLS_ANNOUNCEMENT,
  CONTEXTVM_RESOURCES_ANNOUNCEMENT: gen.CONTEXTVM_RESOURCES_ANNOUNCEMENT,
  CONTEXTVM_RESOURCE_TEMPLATES_ANNOUNCEMENT: gen.CONTEXTVM_RESOURCE_TEMPLATES_ANNOUNCEMENT,
  CONTEXTVM_PROMPTS_ANNOUNCEMENT: gen.CONTEXTVM_PROMPTS_ANNOUNCEMENT,
  RELAY_SET: gen.NIP51_RELAY_SET,
  WORKER_ADVERTISEMENT: gen.LOOM_WORKER_ADVERTISEMENT,
  STATE_SCHEMAS: gen.BAHIA_STATE_SCHEMAS,
  DNS_STATE_SCHEMAS: gen.DNS_STATE_SCHEMAS,
  AUDIT_SCHEMA: gen.BAHIA_AUDIT_SCHEMA,
  SYSTEM_DISCOVERY_SCHEMA: gen.BAHIA_SYSTEM_DISCOVERY_SCHEMA,
  RELAY_SET_SCHEMA: gen.BAHIA_RELAY_SET_SCHEMA,
  SBOM_REFERENCE_SCHEMA: gen.BAHIA_SBOM_REFERENCE_SCHEMA,
  SBOM_AVAILABLE_LIST_SCHEMA: gen.BAHIA_SBOM_AVAILABLE_LIST_SCHEMA,
  SBOM_ATTESTATION_SCHEMA: gen.BAHIA_SBOM_ATTESTATION_SCHEMA,
  SBOM_INDEX_SCHEMA: gen.BAHIA_SBOM_INDEX_SCHEMA
};
