import { KINDS } from './kinds.js';

export const BAHIA_READ_MODEL_KINDS = [
  KINDS.BAHIA_SERVICE_REGISTRY,
  KINDS.BAHIA_ENVIRONMENT_REGISTRY,
  KINDS.BAHIA_SERVICE_STATE,
  KINDS.BAHIA_LLM_ROUTE_REGISTRY,
  KINDS.BAHIA_LLM_ROUTE_STATE,
  KINDS.BAHIA_ARTIFACT_REGISTRY,
  KINDS.BAHIA_DEPLOYMENT_INTENT_REGISTRY,
  KINDS.BAHIA_DEPLOYMENT_RUN_REGISTRY,
  KINDS.BAHIA_BUILD_REGISTRY,
  KINDS.BAHIA_POLICY_REGISTRY,
  KINDS.BAHIA_PACKAGE_REPOSITORY_REGISTRY,
  KINDS.BAHIA_PACKAGE_ARTIFACT_REGISTRY,
  KINDS.BAHIA_PACKAGE_PROMOTION_REGISTRY,
  KINDS.BAHIA_DNS_ZONE_STATE,
  KINDS.BAHIA_DNS_ENDPOINT_STATE,
  KINDS.BAHIA_DNS_POLICY_STATE,
  KINDS.BAHIA_DNS_BACKEND_STATE,
  KINDS.BAHIA_WORKER_STATE,
  KINDS.BAHIA_WORKER_ASSIGNMENT_STATE,
  KINDS.BAHIA_WORKER_DRAIN_STATUS,
  KINDS.BAHIA_WORKER_ELIGIBILITY_PREVIEW,
  KINDS.BAHIA_LEGACY_WORKER_STATE,
  KINDS.BAHIA_LEGACY_WORKER_ASSIGNMENT_STATE,
  KINDS.BAHIA_LEGACY_WORKER_DRAIN_STATUS,
  KINDS.BAHIA_LEGACY_WORKER_ELIGIBILITY_PREVIEW,
  KINDS.LOOM_WORKER_AD,
  // Inference
  KINDS.BAHIA_ML_MODEL_REGISTRY,
  KINDS.BAHIA_ML_MODEL_VERSION_REGISTRY,
  KINDS.BAHIA_ML_ENDPOINT_REGISTRY,
  KINDS.BAHIA_ML_ENDPOINT_STATE,
  KINDS.BAHIA_ML_RUNTIME_CAPABILITY,
  // Backup
  KINDS.BAHIA_BACKUP_DEFINITION_REGISTRY,
  KINDS.BAHIA_BACKUP_POLICY_REGISTRY,
  KINDS.BAHIA_BACKUP_REPOSITORY_REGISTRY,
  KINDS.BAHIA_BACKUP_RETENTION_REGISTRY,
  KINDS.BAHIA_BACKUP_RECIPE_REGISTRY,
  KINDS.BAHIA_BACKUP_RUN_STATE,
  KINDS.BAHIA_BACKUP_VERIFICATION_STATE,
  KINDS.BAHIA_BACKUP_RESTORE_STATE,
  KINDS.BAHIA_BACKUP_RUNTIME_OBSERVATION_STATE
];

export const BAHIA_STATUS_KINDS = [
  KINDS.BAHIA_DNS_OPERATION_STATUS,
  KINDS.BAHIA_DNS_ZONE_CREATE_RESULT,
  KINDS.BAHIA_DNS_POLICY_APPLY_RESULT,
  KINDS.BAHIA_DNS_RECORD_OVERRIDE_RESULT,
  KINDS.BAHIA_DNS_DRIFT_REMEDIATE_RESULT,
  KINDS.BAHIA_DEPLOYMENT_STATUS,
  KINDS.BAHIA_SERVICE_STATUS,
  KINDS.BAHIA_LLM_DEPLOYMENT_STATUS,
  KINDS.BAHIA_PACKAGE_STATUS,
  KINDS.BAHIA_WORKER_STATUS,
  KINDS.BAHIA_DEPLOYMENT_RESULT,
  KINDS.BAHIA_ACTION_RESULT,
  KINDS.BAHIA_SERVICE_CREATE_RESULT,
  KINDS.BAHIA_ENVIRONMENT_CREATE_RESULT,
  KINDS.BAHIA_OBSERVATION_RESULT,
  KINDS.BAHIA_REMEDIATION_RESULT,
  KINDS.BAHIA_LLM_ROUTE_CREATE_RESULT,
  KINDS.BAHIA_LLM_RELEASE_REGISTER_RESULT,
  KINDS.BAHIA_LLM_DEPLOYMENT_RESULT,
  KINDS.BAHIA_PACKAGE_RESULT,
  KINDS.BAHIA_PACKAGE_DRIFT_EVENT,
  KINDS.BAHIA_WORKER_RESULT,
  KINDS.BAHIA_BACKUP_RUN_STATUS,
  KINDS.BAHIA_BACKUP_RESTORE_STATUS,
  KINDS.BAHIA_BACKUP_VERIFICATION_STATUS,
  KINDS.BAHIA_BACKUP_OBSERVATION,
  KINDS.BAHIA_BACKUP_RUN_RESULT,
  KINDS.BAHIA_BACKUP_VERIFICATION_RESULT,
  KINDS.BAHIA_BACKUP_RESTORE_RESULT,
  KINDS.BAHIA_BACKUP_RESTORE_APPROVAL_RESULT,
  KINDS.BAHIA_BACKUP_RETENTION_RESULT,
  KINDS.BAHIA_BACKUP_REPOSITORY_REGISTER_RESULT,
  KINDS.BAHIA_BACKUP_POLICY_APPLY_RESULT,
  KINDS.BAHIA_BACKUP_RECIPE_APPLY_RESULT,
  KINDS.BAHIA_BACKUP_DEFINITION_APPLY_RESULT,
  KINDS.BAHIA_BACKUP_REPOSITORY_PROBE_RESULT
];

export const BAHIA_SBOM_KINDS = [
  KINDS.SBOM_ATTESTATION,
  KINDS.SBOM_INDEX
];

export const BAHIA_AUDIT_KINDS = Array.from({ length: 100 }, (_, i) => 31000 + i);

export const BAHIA_CONTROLPLANE_KINDS = [
  ...BAHIA_READ_MODEL_KINDS,
  ...BAHIA_STATUS_KINDS,
  ...BAHIA_AUDIT_KINDS,
  ...BAHIA_SBOM_KINDS
];
