/**
 * DEPRECATED: Import from ./kinds.gen.js instead.
 * This file is maintained for backward compatibility only.
 */
import * as gen from './kinds.gen.js';

// Re-export all generated constants and functions
export * from './kinds.gen.js';

// Legacy KINDS object for backward compatibility with existing code
// Maps the old naming convention to the new generated constants
export const KINDS = {
  SOUL_TEMPLATE: 31950,
  AGENT_SOUL: 31951,
  SOUL_DRAFT: 31952,
  PROVISIONING_REQUEST: 5950,
  PROVISIONING_STATUS: 6950,
  PROVISIONING_RESULT: 7950,
  SOUL_ACTION: 1950,
  SOUL_ACTION_LEGACY_RESULT: 1951,
  RUNTIME_CAPABILITY: 30317,
  RUNTIME_CONTROL_REQUEST: 38384,
  RUNTIME_CONTROL_RESULT: 38386,
  REPOSITORY: 30617,

  // Bahia canonical control-plane/read-model kinds
  BAHIA_REQUEST_DNS_ZONE_CREATE: gen.DNS_ZONE_CREATE_REQUEST,
  BAHIA_REQUEST_DNS_POLICY_APPLY: gen.DNS_POLICY_APPLY_REQUEST,
  BAHIA_REQUEST_DNS_RECORD_OVERRIDE: gen.DNS_RECORD_OVERRIDE_REQUEST,
  BAHIA_REQUEST_DNS_DRIFT_REMEDIATE: gen.DNS_DRIFT_REMEDIATE_REQUEST,
  BAHIA_DNS_OPERATION_STATUS: gen.DNS_OPERATION_STATUS,
  BAHIA_DNS_ZONE_CREATE_RESULT: gen.DNS_ZONE_CREATE_RESULT,
  BAHIA_DNS_POLICY_APPLY_RESULT: gen.DNS_POLICY_APPLY_RESULT,
  BAHIA_DNS_RECORD_OVERRIDE_RESULT: gen.DNS_RECORD_OVERRIDE_RESULT,
  BAHIA_DNS_DRIFT_REMEDIATE_RESULT: gen.DNS_DRIFT_REMEDIATE_RESULT,
  BAHIA_REQUEST_DEPLOY: gen.DEPLOY_REQUEST,
  BAHIA_REQUEST_ROLLBACK: gen.ROLLBACK_REQUEST,
  BAHIA_REQUEST_SERVICE_ACTION: gen.SERVICE_ACTION,
  BAHIA_REQUEST_SERVICE_CREATE: gen.SERVICE_CREATE,
  BAHIA_REQUEST_ENVIRONMENT_CREATE: gen.ENVIRONMENT_CREATE,
  BAHIA_REQUEST_DEPLOYMENT_APPROVAL: gen.DEPLOYMENT_APPROVAL,
  BAHIA_REQUEST_OBSERVATION_SUBMIT: gen.OBSERVATION_SUBMIT,
  BAHIA_REQUEST_DRIFT_REMEDIATE: gen.DRIFT_REMEDIATE,
  BAHIA_REQUEST_LLM_ROUTE_CREATE: gen.LLM_ROUTE_CREATE,
  BAHIA_REQUEST_LLM_RELEASE_REGISTER: gen.LLM_RELEASE_REGISTER,
  BAHIA_REQUEST_LLM_DEPLOY: gen.LLM_DEPLOY_REQUEST,
  BAHIA_REQUEST_LLM_DEPLOYMENT_APPROVAL: gen.LLM_DEPLOYMENT_APPROVAL,
  BAHIA_REQUEST_LLM_ROLLBACK: gen.LLM_ROLLBACK_REQUEST,
  BAHIA_REQUEST_SERVICE_UPDATE: gen.SERVICE_UPDATE,
  BAHIA_REQUEST_SERVICE_DELETE: gen.SERVICE_DELETE,
  BAHIA_REQUEST_ENVIRONMENT_UPDATE: gen.ENVIRONMENT_UPDATE,
  BAHIA_REQUEST_ENVIRONMENT_DELETE: gen.ENVIRONMENT_DELETE,
  BAHIA_REQUEST_ARTIFACT_REGISTER: gen.ARTIFACT_REGISTER,
  BAHIA_REQUEST_POLICY_CREATE: gen.POLICY_CREATE,
  BAHIA_REQUEST_POLICY_UPDATE: gen.POLICY_UPDATE,
  BAHIA_REQUEST_POLICY_DELETE: gen.POLICY_DELETE,
  BAHIA_REQUEST_POLICY_EVALUATE: gen.POLICY_EVALUATE,
  BAHIA_REQUEST_PACKAGE_PROMOTE: gen.PACKAGE_PROMOTION_REQUEST,
  BAHIA_REQUEST_PACKAGE_YANK: gen.PACKAGE_YANK_REQUEST,
  BAHIA_REQUEST_WORKER_CORDON: gen.WORKER_CORDON_REQUEST,
  BAHIA_REQUEST_WORKER_UNCORDON: gen.WORKER_UNCORDON_REQUEST,
  BAHIA_REQUEST_WORKER_DRAIN: gen.WORKER_DRAIN_REQUEST,
  BAHIA_REQUEST_WORKER_UNDRAIN: gen.WORKER_UNDRAIN_REQUEST,
  BAHIA_REQUEST_WORKER_MAINTENANCE_ENTER: gen.WORKER_MAINTENANCE_ENTER,
  BAHIA_REQUEST_WORKER_MAINTENANCE_EXIT: gen.WORKER_MAINTENANCE_EXIT,
  BAHIA_REQUEST_WORKER_LABELS_UPDATE: gen.WORKER_LABELS_UPDATE,
  BAHIA_REQUEST_WORKER_POLICY_APPLY: gen.WORKER_POLICY_APPLY_REQUEST,
  BAHIA_REQUEST_WORKLOAD_PIN: gen.WORKLOAD_PIN_REQUEST,
  BAHIA_REQUEST_WORKER_CLEANUP: gen.WORKER_CLEANUP_REQUEST,
  BAHIA_PACKAGE_STATUS: gen.PACKAGE_STATUS,
  BAHIA_WORKER_STATUS: gen.WORKER_STATUS,
  BAHIA_PACKAGE_RESULT: gen.PACKAGE_RESULT,
  BAHIA_PACKAGE_DRIFT_EVENT: gen.PACKAGE_DRIFT_EVENT,
  BAHIA_WORKER_RESULT: gen.WORKER_RESULT,
  BAHIA_DEPLOYMENT_STATUS: gen.DEPLOYMENT_STATUS,
  BAHIA_SERVICE_STATUS: gen.SERVICE_STATUS,
  BAHIA_LLM_DEPLOYMENT_STATUS: gen.LLM_DEPLOYMENT_STATUS,
  BAHIA_DEPLOYMENT_RESULT: gen.DEPLOYMENT_RESULT,
  BAHIA_ACTION_RESULT: gen.ACTION_RESULT,
  BAHIA_SERVICE_CREATE_RESULT: gen.SERVICE_CREATE_RESULT,
  BAHIA_ENVIRONMENT_CREATE_RESULT: gen.ENVIRONMENT_CREATE_RESULT,
  BAHIA_OBSERVATION_RESULT: gen.OBSERVATION_RESULT,
  BAHIA_REMEDIATION_RESULT: gen.REMEDIATION_RESULT,
  BAHIA_LLM_ROUTE_CREATE_RESULT: gen.LLM_ROUTE_CREATE_RESULT,
  BAHIA_LLM_RELEASE_REGISTER_RESULT: gen.LLM_RELEASE_REGISTER_RESULT,
  BAHIA_LLM_DEPLOYMENT_RESULT: gen.LLM_DEPLOYMENT_RESULT,
  BAHIA_SERVICE_STATE: gen.SERVICE_STATE,
  BAHIA_SERVICE_REGISTRY: gen.SERVICE_REGISTRY,
  BAHIA_ENVIRONMENT_REGISTRY: gen.ENVIRONMENT_REGISTRY,
  BAHIA_LLM_ROUTE_REGISTRY: gen.LLM_ROUTE_REGISTRY,
  BAHIA_LLM_ROUTE_STATE: gen.LLM_ROUTE_STATE,
  BAHIA_ARTIFACT_REGISTRY: gen.ARTIFACT_REGISTRY,
  BAHIA_DEPLOYMENT_INTENT_REGISTRY: gen.DEPLOYMENT_INTENT_REGISTRY,
  BAHIA_DEPLOYMENT_RUN_REGISTRY: gen.DEPLOYMENT_RUN_REGISTRY,
  BAHIA_BUILD_REGISTRY: gen.BUILD_REGISTRY,
  BAHIA_POLICY_REGISTRY: gen.POLICY_REGISTRY,
  BAHIA_PACKAGE_REPOSITORY_REGISTRY: gen.PACKAGE_REPOSITORY_REGISTRY,
  BAHIA_PACKAGE_ARTIFACT_REGISTRY: gen.PACKAGE_ARTIFACT_REGISTRY,
  BAHIA_PACKAGE_PROMOTION_REGISTRY: gen.PACKAGE_PROMOTION_REGISTRY,
  BAHIA_SYSTEM_DISCOVERY: gen.SYSTEM_DISCOVERY,
  BAHIA_DNS_ZONE_STATE: gen.DNS_ZONE_STATE,
  BAHIA_DNS_ENDPOINT_STATE: gen.DNS_ENDPOINT_STATE,
  BAHIA_DNS_POLICY_STATE: gen.DNS_POLICY_STATE,
  BAHIA_DNS_BACKEND_STATE: gen.DNS_BACKEND_STATE,
  BAHIA_WORKER_STATE: gen.WORKER_STATE,
  BAHIA_WORKER_ASSIGNMENT_STATE: gen.WORKER_ASSIGNMENT_STATE,
  BAHIA_WORKER_DRAIN_STATUS: gen.WORKER_DRAIN_STATUS,
  BAHIA_WORKER_ELIGIBILITY_PREVIEW: gen.WORKER_ELIGIBILITY_PREVIEW,
  BAHIA_LEGACY_WORKER_STATE: gen.LEGACY_WORKER_STATE,
  BAHIA_LEGACY_WORKER_ASSIGNMENT_STATE: gen.LEGACY_WORKER_ASSIGNMENT_STATE,
  BAHIA_LEGACY_WORKER_DRAIN_STATUS: gen.LEGACY_WORKER_DRAIN_STATUS,
  BAHIA_LEGACY_WORKER_ELIGIBILITY_PREVIEW: gen.LEGACY_WORKER_ELIGIBILITY_PREVIEW,
  NIP51_RELAY_SET: gen.RELAY_SET_DISCOVERY,
  LOOM_WORKER_AD: gen.LOOM_WORKER_ADVERTISEMENT,

  // Inference read-model kinds (31980-31989)
  BAHIA_ML_MODEL_REGISTRY: gen.ML_MODEL_REGISTRY,
  BAHIA_ML_MODEL_VERSION_REGISTRY: gen.ML_MODEL_VERSION_REGISTRY,
  BAHIA_ML_DATASET_REGISTRY: gen.ML_DATASET_REGISTRY,
  BAHIA_ML_RECIPE_REGISTRY: gen.ML_RECIPE_REGISTRY,
  BAHIA_ML_RECIPE_RUN_STATE: gen.ML_RECIPE_RUN_STATE,
  BAHIA_ML_ENDPOINT_REGISTRY: gen.ML_INFERENCE_ENDPOINT_REGISTRY,
  BAHIA_ML_ENDPOINT_STATE: gen.ML_INFERENCE_ENDPOINT_STATE,
  BAHIA_ML_EVALUATION_STATE: gen.ML_EVALUATION_EXPERIMENT_STATE,
  BAHIA_ML_ARTIFACT_PROVENANCE: gen.ML_ARTIFACT_PROVENANCE_GRAPH,
  BAHIA_ML_RUNTIME_CAPABILITY: gen.ML_RUNTIME_CAPABILITY_PROFILE,

  // Backup control-plane command, result, status, attestation, and read-model kinds
  BAHIA_REQUEST_BACKUP_RUN: gen.BACKUP_RUN_REQUEST,
  BAHIA_REQUEST_BACKUP_VERIFICATION: gen.BACKUP_VERIFICATION_REQUEST,
  BAHIA_REQUEST_BACKUP_RESTORE: gen.BACKUP_RESTORE_REQUEST,
  BAHIA_REQUEST_BACKUP_RESTORE_APPROVAL: gen.BACKUP_RESTORE_APPROVAL,
  BAHIA_REQUEST_BACKUP_RETENTION: gen.BACKUP_RETENTION_ENFORCE,
  BAHIA_REQUEST_BACKUP_REPOSITORY_REGISTER: gen.BACKUP_REPOSITORY_REGISTER,
  BAHIA_REQUEST_BACKUP_POLICY_APPLY: gen.BACKUP_POLICY_APPLY,
  BAHIA_REQUEST_BACKUP_RECIPE_APPLY: gen.BACKUP_RECIPE_APPLY,
  BAHIA_REQUEST_BACKUP_DEFINITION_APPLY: gen.BACKUP_DEFINITION_APPLY,
  BAHIA_REQUEST_BACKUP_REPOSITORY_PROBE: gen.BACKUP_REPOSITORY_PROBE,
  BAHIA_BACKUP_RUN_RESULT: gen.BACKUP_RUN_RESULT,
  BAHIA_BACKUP_VERIFICATION_RESULT: gen.BACKUP_VERIFICATION_RESULT,
  BAHIA_BACKUP_RESTORE_RESULT: gen.BACKUP_RESTORE_RESULT,
  BAHIA_BACKUP_RESTORE_APPROVAL_RESULT: gen.BACKUP_RESTORE_APPROVAL_RESULT,
  BAHIA_BACKUP_RETENTION_RESULT: gen.BACKUP_RETENTION_RESULT,
  BAHIA_BACKUP_REPOSITORY_REGISTER_RESULT: gen.BACKUP_REPOSITORY_REGISTER_RESULT,
  BAHIA_BACKUP_POLICY_APPLY_RESULT: gen.BACKUP_POLICY_APPLY_RESULT,
  BAHIA_BACKUP_RECIPE_APPLY_RESULT: gen.BACKUP_RECIPE_APPLY_RESULT,
  BAHIA_BACKUP_DEFINITION_APPLY_RESULT: gen.BACKUP_DEFINITION_APPLY_RESULT,
  BAHIA_BACKUP_REPOSITORY_PROBE_RESULT: gen.BACKUP_REPOSITORY_PROBE_RESULT,
  BAHIA_BACKUP_RUN_STATUS: gen.BACKUP_RUN_STATUS,
  BAHIA_BACKUP_RESTORE_STATUS: gen.BACKUP_RESTORE_STATUS,
  BAHIA_BACKUP_VERIFICATION_STATUS: gen.BACKUP_VERIFICATION_STATUS,
  BAHIA_BACKUP_OBSERVATION: gen.BACKUP_OBSERVATION,
  BAHIA_BACKUP_RUN_ATTESTATION: gen.BACKUP_RUN_ATTESTATION,
  BAHIA_BACKUP_VERIFICATION_ATTESTATION: gen.BACKUP_VERIFICATION_ATTESTATION,
  BAHIA_BACKUP_DEFINITION_REGISTRY: gen.BACKUP_DEFINITION_REGISTRY,
  BAHIA_BACKUP_POLICY_REGISTRY: gen.BACKUP_POLICY_REGISTRY,
  BAHIA_BACKUP_REPOSITORY_REGISTRY: gen.BACKUP_REPOSITORY_REGISTRY,
  BAHIA_BACKUP_RETENTION_REGISTRY: gen.BACKUP_RETENTION_REGISTRY,
  BAHIA_BACKUP_RECIPE_REGISTRY: gen.BACKUP_RECIPE_REGISTRY,
  BAHIA_BACKUP_RUN_STATE: gen.BACKUP_RUN_STATE,
  BAHIA_BACKUP_VERIFICATION_STATE: gen.BACKUP_VERIFICATION_STATE,
  BAHIA_BACKUP_RESTORE_STATE: gen.BACKUP_RESTORE_STATE,
  BAHIA_BACKUP_RUNTIME_OBSERVATION_STATE: gen.BACKUP_RUNTIME_OBSERVATION_STATE,

  // Operator assistant event kinds
  ASSISTANT_SESSION: gen.ASSISTANT_SESSION,
  ASSISTANT_PROMPT_REQUEST: gen.ASSISTANT_PROMPT_REQUEST,
  ASSISTANT_APPROVAL: gen.ASSISTANT_APPROVAL,
  ASSISTANT_STATUS: gen.ASSISTANT_STATUS,
  ASSISTANT_RESULT: gen.ASSISTANT_RESULT,

  // SBOM Attestation/Index kinds (NIP-51 style parameterized lists)
  SBOM_ATTESTATION: gen.SBOM_ATTESTATION,
  SBOM_INDEX: gen.SBOM_INDEX
};

export const SOUL_FACTORY_RUNTIME_CONTROL_SCHEMA = 'soulfactory-runtime-control/v1';
export const SOUL_FACTORY_RUNTIME_CAPABILITY_SCHEMA = 'soulfactory-runtime-capability/v1';

export const SOUL_RUNTIME_TARGETS = {
  OPENCLAW: 'openclaw',
  METIQ: 'metiq'
};

export const SOUL_LIFECYCLE_ACTIONS = {
  SUSPEND: 'suspend',
  RESUME: 'resume',
  REVOKE: 'revoke',
  REGENERATE: 'regenerate',
  REDEPLOY: 'redeploy',
  UPDATE: 'update'
};

export const SOUL_RUNTIME_METHODS = {
  PROVISION: 'soulfactory.provision',
  UPDATE: 'soulfactory.update',
  SUSPEND: 'soulfactory.suspend',
  RESUME: 'soulfactory.resume',
  REDEPLOY: 'soulfactory.redeploy',
  REVOKE: 'soulfactory.revoke'
};

export function isLifecycleResultKind(kind) {
  return kind === KINDS.PROVISIONING_RESULT || kind === KINDS.SOUL_ACTION_LEGACY_RESULT;
}

export function canonicalLifecycleResultKind(kind) {
  return kind === KINDS.SOUL_ACTION_LEGACY_RESULT ? KINDS.PROVISIONING_RESULT : kind;
}
